import Foundation

extension LocalizationManager {
    static let englishDict: [String: String] = [
            "language": "Language",
            "select_language": "Select Language",
            "network": "Network",
            "lines": "Lines",
            "trains": "Trains",
            "materiale_rotabile": "Rolling Stock",
            "railway_ai": "Railway AI",
            "io": "I/O",
            "visualization": "Visualization",
            "diagnostics": "Diagnostics",
            "ai_config": "AI Configuration",
            "performance": "Performance",
            "global_line_width": "Global Line Width",
            "global_font_size": "Global Font Size",
            "track_widths": "Track Widths",
            "track_single": "Single Track",
            "track_double": "Double Track",
            "track_regional": "Regional Track",
            "track_highspeed": "High Speed",
            "train_params": "Train Parameters",
            "max_speed": "Max Speed (km/h)",
            "acceleration": "Acceleration (m/s²)",
            "deceleration": "Deceleration (m/s²)",
            "priority": "Priority (1-10)",
            "track_speed_limits": "Track Speed Limits",
            "station": "Station",
            "interchange": "Interchange",
            "depot": "Depot",
            "junction": "Junction",
            "export": "Export",
            "print": "Print",
            "undo": "Undo",
            "redo": "Redo",
            "save": "Save",
            "delete": "Delete",
            "edit": "Edit",
            "add": "Add",
            "search": "Search...",
            "delete_all": "Delete All",
            "delete_all_confirm_title": "Confirm Deletion",
            "delete_all_confirm_message": "Are you sure you want to delete all items? This action cannot be undone.",
            "stations": "Stations",
            "tracks": "Tracks",
            "vehicles": "Vehicles",
            "track_display_name": "Track",
            "station_creation_placeholder": "Station Creation (coming soon)",
            "track_creation_placeholder": "Track Creation (coming soon)",
            "train_creation_placeholder": "Train Creation (coming soon)",
            "vehicle_creation_placeholder": "Vehicle Creation (coming soon)",
            "name": "Name",
            "type": "Type",
            "capacity": "Capacity",
            "platforms": "Platforms",
            "departure": "Departure",
            "arrival": "Arrival",
            "dwell_time": "Dwell (min)",
            "track": "Track",
            "no_trains": "No Trains",
            "no_stations": "No Stations",
            "no_lines": "No Lines",
            "loading": "Loading...",
            "error": "Error",
            "success": "Success",
            "confirm": "Confirm",
            "file_management": "File Management",
            "conflitto_capacita_fmt": "Conflict between %@ and %@ at %@. Resource: %@ (Capacity: %d). Time: %@ - %@",
            "instradamento_non_consentito_fmt": "Train %@ is using an unauthorized track at %@",
            "save_project": "Save Project",
            "save_infrastructure": "Save Infrastructure",
            "save_infrastructure_desc": "Stations and tracks only",
            "import_infrastructure": "Import Infrastructure",
            "import_infrastructure_desc": "Stations and tracks only (JSON)",
            "open_project": "Open Project",
            "save_local": "Save Current State",
            "save_local_desc": "Quick save to local database",
            "legacy_integration": "Legacy Integration",
            "legacy_footer": "Import files from previous versions (FDC 1.x) to convert them to the Pignolo protocol.",
            "import_old": "Import Old FDC (.fdc)",
            "export_new": "Export Pignolo V2 (.rail)",
            "io_title": "I/O Data",
            "support_format": "Supports .rail, .fdc, .json",
            "station_json_import": "Add Stations (JSON)",
            "station_json_import_desc": "Paste a JSON snippet of objects (comments allowed) to add stations to the network.",
            "station_json_placeholder": "{ \"id\": \"NEW_01\", \"name\": \"Station\", \"latitude\": 0.0, \"longitude\": 0.0, \"type\": \"station\" }",
            "station_json_add_button": "Add Stations",
            "station_json_empty": "Paste a valid JSON snippet first.",
            "station_json_result_fmt": "Stations added: %d. Skipped: %d.",
            "station_json_error_fmt": "JSON error: %@",
            "done": "Done",
            "cancel": "Cancel",
            "show_all": "Show All",
            "filter": "Filter",
            "search_station": "Search station...",
            "empty_line": "Empty Line",
            "no_connection": "No Connection",
            "show_all_anyway": "Show all stations anyway",
            "must_create_stations": "You must first create stations in the 'Network' section.",
            "select_station": "Select Station",
            "edit_station": "Edit Station",
            "close": "Close",
            "delete_station": "Delete Station",
            "delete_confirm": "Are you sure you want to delete this station? This action cannot be undone.",
            "station_data": "Station Data",
            "station_name": "Station Name",
            "functional_type": "Functional Type",
            "standard_station": "Standard Station",
            "platform_count": "Platform Count",
            "hubs_interchanges": "Hubs & Interchanges",
            "belongs_to_hub": "Belongs to HUB",
            "no_hub": "No HUB (Independent)",
            "visual_style": "Visual Style",
            "coordinates": "Coordinates",
            "latitude": "Latitude",
            "longitude": "Longitude",
            "move_mode": "Move Mode",
            "move_mode_on": "ACTIVE: You can drag the station on the map or type coordinates.",
            "move_mode_off": "INACTIVE: Position is locked to prevent accidental moves. Enable to edit.",
            "custom_color": "Custom Color",
            "details": "Details",
            "general_options": "General Options",
            "show_grid": "Show Grid",
            "use_cloud_ai": "Conflict Resolution via Cloud AI",
            "sizes": "Sizes",
            "line_width_px": "Line Width: %d px",
            "font_size_pt": "Font Size: %d pt",
            "track_widths_map": "Track Widths on Map",
            "track_single_px": "Single Track: %.1f px",
            "track_double_px": "Double Track: %.1f px",
            "track_regional_px": "Regional Track: %.1f px",
            "track_highspeed_px": "High Speed Track: %.1f px",
            "reset_defaults": "Reset to Defaults",
            "map_preview": "Map Preview",
            "example_station": "EXAMPLE STATION",
            "regional_line": "Regional Line",
            "edge_representation": "Link Representation",
            "server_config": "Server Configuration",
            "api_base_url": "Server API Base URL",
            "restore_default_url": "Restore default URL",
            "username": "Username",
            "password": "Password",
            "permanent_api_key": "Permanent API Key",
            "auth_footer": "Use Password for temporary login or API Key for permanent access.",
            "authentication": "Authentication",
            "test_login": "Test Login",
            "generate_api_key": "Generate API Key",
            "login_success": "Login Successful! Token saved.",
            "login_error": "Login Error: %@",
            "api_key_generated": "API Key Generated and Saved!",
            "api_key_error": "Error Generating Key: %@",
            "ai_api_key_auth": "API Key Authentication",
            "ai_get_key_instruction": "To get your API Key:",
            "ai_step_1": "1. Go to the Railway AI dashboard",
            "ai_step_2": "2. Login with your credentials",
            "ai_step_3": "3. Copy your API Key from the dashboard",
            "ai_step_4": "4. Paste it in the field above",
            "ai_open_dashboard": "Open Railway AI Dashboard",
            "ai_verify_key": "Verify API Key",
            "ai_key_invalid": "Invalid API Key: %@",
            "ai_key_valid_fmt": "✓ Valid API Key - User: %@ - Expires in: %d days",
            "ai_key_expiring_fmt": "⚠️ Warning: Key expires in %d days!",
            "diagnostics_and_info": "Diagnostics & Info",
            "show_network_logs": "Show Network Logs",
            "info": "Information",
            "credits_author": "Credits & Author",
            "debug_data_json": "Debug Data (JSON)",
            "show_json_lines": "Show Line JSON",
            "show_json_trains": "Show Train JSON",
            "hub_position": "Hub Position",
            "hub_standard_pos": "Standard (Bottom Left)",
            "hub_logic_description": "This station is logically linked to another. It will be treated as a rapid interchange point.",
            "track_properties": "Track Properties",
            "distance_km": "Distance (km)",
            "distance": "Distance",
            "max_speed_kmh": "Max Speed (km/h)",
            "speed": "Speed",
            "track_type": "Track Type",
            "capacity_trains_h": "Capacity (trains/h)",
            "delete_track": "Delete Track",
            "edit_track": "Edit Track",
            "delete_track_confirm": "Are you sure you want to delete this track? This action cannot be undone.",
            "selection": "Selection",
            "trains_selected_count": "%d trains selected",
            "plus_others_count": "+ others %d",
            "quick_actions": "Quick Actions",
            "shift_time_minutes": "Shift Time: %@%d min",
            "apply_shift": "Apply Shift",
            "delete_selected": "Delete Selected",
            "batch_edit": "Batch Edit",
            "delete_trains": "Delete Trains",
            "delete_trains_confirm": "Are you sure you want to delete %d trains? This action is not reversible.",
            "select_category": "Select a category",
            "exporting_in_progress": "Exporting in progress...",
            "current_screen": "Current Screen",
            "export_jpg": "Export JPG",
            "export_pdf": "Export PDF",
            "map": "Map",
            "high_res_map": "High Resolution Map",
            "print_job_map": "FdC Map Print",
            "stations_count": "Stations (%d)",
            "tracks_count": "Tracks (%d)",
            "edit_line": "Edit Line",
            "delete_line": "Delete Line",
            "no_trains_assigned": "No trains assigned to this line.",
            "unassigned_trains": "Unassigned Trains",
            "schedule_management": "Schedule Management",
            "delete_all_trains": "Delete All Trains",
            "delete_all_trains_help": "Delete all trains from the system (including ghost trains)",
            "ai_suggestion_alert": "AI Suggestion",
            "ok": "Ok",
            "default_train_params": "Default Train Parameters",
            "new_train_params_desc": "These parameters are used when creating a new train",
            "regional_train": "Regional Train",
            "intercity_train": "Intercity Train",
            "highspeed_train": "High Speed Train",
            "max_speed_label": "Max Speed:",
            "acceleration_label": "Acceleration:",
            "deceleration_label": "Deceleration:",
            "priority_label": "Priority:",
            "track_speed_limits_section": "Track Speed Limits",
            "track_speed_limits_desc": "Speed limits for track types",
            "train_track_params_title": "Train & Track Parameters",
            "path_composition": "Path Composition",
            "line_details": "Infrastructure Details",
            "line_name_placeholder": "Infrastructure Line Name",
            "route_details": "Route Details",
            "route_name_placeholder": "Route Name (e.g. London-Paris)",
            "code_prefix_placeholder": "Code Prefix (e.g. RE)",
            "number_prefix_placeholder": "Numeric Prefix",
            "line_color": "Infrastructure Color",
            "route_color": "Route Color",
            "new_line": "New Infrastructure Line",
            "new_route": "New Route",
            "line_name_example": "Line Name (e.g. EC Tirrenica Sud)",
            "number_prefix_example": "Numeric Prefix (e.g. 5)",
            "train_details": "Train Details",
            "number": "Number",
            "name_optional": "Name (optional)",
            "train_type_picker": "Type",
            "departure_picker": "Departure",
            "selected_line": "Selected Line",
            "stop_sequence": "Stop Sequence",
            "select_terminals_desc": "Select terminals or add manually",
            "add_stop_manual": "Add manual stop",
            "new_trip": "New Trip",
            "create": "Create",
            "train_name_default": "Train %d",
            "freight_train": "Freight Train",
            "support_train": "Support Train",
            "developed_by": "Developed by",
            "version_label": "Version %@",
            "project_info_title": "Project Information",
            "project_description": "FdC Railway Manager is an advanced tool for management, simulation, and optimization of local railway networks. It integrates pathfinding algorithms, conflict detection, and artificial intelligence to ensure efficient and safe schedules.",
            "technologies_used": "Technologies used:",
            "reactive_interface": "Reactive Interface",
            "ml_optimization": "ML Optimization",
            "geographic_visualization": "Geographic Visualization",
            "credits": "Credits",
            "no_stations_system": "There are no stations registered in the system.",
            "line_no_stations": "This railway line has no stations assigned yet. Add them in the 'Lines' tab.",
            "no_connected_tracks": "There are no tracks connecting the last selected station to other nodes. Draw a track or show all stations.",
            "no_stations_criteria": "No stations match the search criteria.",
            "current_project": "Current Project",
            "unnamed_network": "Unnamed Network",
            "stations_count_label": "%d stations",
            "tracks_count_label": "%d tracks",
            "lines_count_label": "%d lines",
            "trains_count_label": "%d trains",
            "last_save": "Last save: %@",
            "quick_save": "Quick Save",
            "save_current_state": "Save Current State",
            "auto_save_local_desc": "Automatic save to local database",
            "import_export_files": "File Import / Export",
            "export_project": "Export Project",
            "save_rail_file_desc": "Save as .rail file (Pignolo V2)",
            "import_project": "Import Project",
            "support_formats_desc": "Supports .rail, .fdc, .railml, .json",
            "legacy_formats": "Legacy Formats",
            "legacy_formats_footer": "Import files created with previous versions (FDC 1.x) to automatically convert them to the new Pignolo V2 protocol.",
            "import_fdc_legacy": "Import Legacy FDC (.fdc)",
            "import_railml": "Import RailML (.railml)",
            "import_error_title": "Import Error",
            "security_scoped_error": "Unable to gain access to the file (Security Scoped Resource)",
            "decode_error": "Unable to decode the file. Format not recognized.",
            "io_management": "I/O Management",
            "smart_scheduling_intel": "Smart Scheduling Intelligence",
            "optimize_button": "Optimize",
            "system_status": "System Status",
            "trains_count": "%d Trains",
            "stations_label": "Stations",
            "segments_label": "Segments",
            "status_label": "Status",
            "waiting_status": "Waiting",
            "optimized_status": "Optimized",
            "proposed_modifications": "Proposed Modifications",
            "no_modifications_needed": "No modifications needed. Optimal schedule.",
            "optimization_analysis": "Optimization Analysis",
            "detected_label": "Detected",
            "resolved_label": "Resolved",
            "remaining_label": "Remaining",
            "residual_conflicts_detail": "Residual Conflicts Detail",
            "total_optimized_time": "Total Optimized Time",
            "ready_for_optimization": "Ready for Optimization",
            "ai_welcome_desc": "Load trains and click Optimize to use RailwayAI and resolve all network conflicts.",
            "ai_analyzing": "AI Analysis in progress...",
            "platform_at": "Platform %d",
            "modification": "Modification",
            "impact_label": "Impact: %ds",
            "trains_to_schedule": "Trains to Schedule",
            "manage_trains": "Manage Trains",
            "type_speed_label": "Type: %@, Max speed: %d km/h",
            "timetable_traffic_sim": "Timetable and Traffic Simulation",
            "calculate_timetables": "Calculate Timetables and Conflicts",
            "calculating_in_progress": "Calculation in progress...",
            "export_result": "Export Result",
            "view_timetable_chart": "View Timetable Chart",
            "local_infrastructure": "Local Infrastructure (FDC Engine)",
            "simulate_full_network": "Simulate Full Network",
            "stops_count_label": "%d stops",
            "conflict_dashboard": "Conflict Dashboard",
            "manual_timetable_edit": "Manual Timetable Editing",
            "edit_timetables_manually": "Edit Timetables Manually",
            "advanced_export_print": "Advanced Export and Print",
            "copy_to_clipboard": "Copy Result to Clipboard",
            "print_result": "Print Result",
            "file_import": "File Import",
            "import_fdc_txt": "Import .fdc or .txt file",
            "timetables_conflicts_result": "Timetables/Conflicts Result",
            "detected_conflicts": "Detected Conflicts",
            "scheduler_title": "Scheduler",
            "import_fdc_button": "Import .fdc",
            "manage_trains_title": "Manage Trains",
            "add_train": "Add Train",
            "new_train": "New Train",
            "train_name": "Train Name",
            "add_button": "Add",
            "timetable_chart_title": "Train Timetable Chart",
            "manual_edit_title": "Manual Timetable and Conflict Edit",
            "print_preview_title": "Print Preview",
            "print_job_scheduler": "Timetables and Conflicts",
            "network_load_error": "Error loading network: %@",
            "network_save_error": "Error saving network: %@",
            "single_trip": "Single Trip",
            "cadenced_trip": "Cadenced",
            "even": "Even",
            "odd": "Odd",
            "outward": "Outward",
            "return": "Return",
            "genetic_opt_gen_fmt": "Genetic Optimization (Gen %d)",
            "conflicts_count_fmt": "%d conflicts",
            "cancelling": "Cancelling...",
            "stop": "Stop",
            "generate": "Generate",
            "schedule_generation": "Schedule Generation",
            "schedule_gen_line_fmt": "Schedule Generation - Line %@",
            "mode": "Mode",
            "from": "From",
            "to": "To",
            "via": "Via",
            "path": "Path",
            "stations_count_fmt": "%d stations",
            "length_short": "Len.",
            "est_duration_short": "Est. duration",
            "duration_min_fmt": "%.1f min",
            "train_type": "Train Type",
            "start_hour": "Start Hour",
            "end_hour": "End Hour",
            "interval": "Interval",
            "interval_min_fmt": "%d min",
            "every_min_fmt": "Every %d min",
            "start_number": "Start Number",
            "num_placeholder": "Num",
            "parity": "Parity",
            "generate_return_trips": "Generate Return Trips",
            "trains_to_be_created_fmt": "%d trains will be created.",
            "optimization_ga": "Optimization (GA)",
            "cloud_ai_active_desc": "Cloud AI Optimization Active (Global).",
            "local_ga_desc": "Local G.A. will adjust departures and dwells to eliminate conflicts.",
            "path_mode": "Path Mode",
            "method": "Method",
            "auto_calculation": "Auto Calculation",
            "manual_composition": "Manual Composition",
            "define_terminals": "Define Terminals",
            "via_passage": "Pass via",
            "add_via_point": "Add via point",
            "invert_path_desc": "Invert Path (B -> A)",
            "calculating_path_desc": "Calculating path...",
            "calculate_proposed_paths": "Calculate Proposed Paths",
            "proposed_path": "Proposed Path",
            "select_dots": "Select...",
            "path_alt_fmt": "%@ (%d stops, %.1f km)",
            "path_found_fmt": "Path found: %@",
            "total_distance": "Total distance:",
            "calculated_itinerary": "Calculated itinerary:",
            "manual_composition_desc": "Use the section below to manage the station sequence.",
            "error_index_not_found_fmt": "Error: Index not found (%d)",
            "unknown_station": "Unknown",
            "error_stations_not_in_line": "Stations not found in selected line.",
            "error_select_terminals": "Select at least a start and end station.",
            "error_no_path_found_fmt": "No path found between %@ and %@.",
            "multi_line_path": "Multi-line Path",
            "error_no_simple_path": "No simple path found connecting all stops.",
            "route_analysis": "Route analysis...",
            "line_analysis": "Infrastructure analysis...",
            "starting_pipeline": "Starting 7-Step Pipeline...",
            "preparation": "Preparation...",
            "sending_to_cloud": "Sending to Cloud...",
            "applying": "Applying...",
            "validation": "Validation...",
            "final_refinement": "Final Refinement...",
            "optimized": "Optimized!",
            "almost_resolved_fmt": "Almost resolved (%d remaining)",
            "filled_star": "Filled Star",
            "filled_square": "Filled Square",
            "empty_square": "Empty Square",
            "filled_circle": "Filled Circle",
            "empty_circle": "Empty Circle",
            "top_left_offset": "Top Left",
            "top_right_offset": "Top Right",
            "bottom_left_offset": "Bottom Left",
            "bottom_right_offset": "Bottom Right",
            "unnamed_line": "Unnamed Line",
            "all_tab": "All",
            "hotspots_tab": "Hotspots",
            "lines_tab": "Lines",
            "line_segments": "Line Segments",
            "nodes_stations": "Nodes/Stations",
            "perfect_timetable": "Perfect Timetable",
            "no_conflicts_desc": "The algorithm has resolved all conflicts. The plan is ready for operation.",
            "conflicts_detected_fmt_short": "%d Conflicts Detected",
            "conflict_analysis_desc": "Temporal collision and saturated resources analysis",
            "criticality": "Criticality",
            "consecutive_collisions": "Consecutive collisions at this point",
            "export_completed": "✅ Export completed",
            "export_error_fmt": "Export error: %@",
            "import_completed_fmt": "✅ Import completed: %@",
            "import_error_fmt": "Load error: %@",
            "railml_parsing_failed": "RailML parsing failed",
            "loaded_rail_file_fmt": "✅ Loaded .rail file: %@",
            "ai_optimizer_fdc": "FDC Optimizer (v1/v2)",
            "solve_conflicts_json": "Solve Conflicts (FDC JSON)",
            "advanced_optimizer_cpp": "Advanced Optimizer (GA C++)",
            "global_optimization_pignolo": "Global Optimization (Pignolo)",
            "conflicts_detected_fmt": "Conflicts detected: %d",
            "total_delay_fmt": "Total delay: %.1f min",
            "planning_assistant_fast": "Planning Assistant (Fast Proposer)",
            "target_lines_fmt": "Target Lines: %d",
            "generate_schedule_proposal": "Generate Schedule Proposal",
            "review_proposals_fmt": "Review Proposals (%d lines)",
            "optimized_solutions": "Optimized Solutions",
            "departure_adj_fmt": "Departure: %@%.1f min",
            "dwells_extended_fmt": "%d extended dwells",
            "schedules_updated_success": "Schedules updated successfully.",
            "apply_schedule_change": "Apply Schedule Change",
            "proposed_solutions": "Proposed Solutions",
            "unknown_train": "Unknown Train",
            "new_departure_fmt": "New Departure: %@",
            "modified_stops_fmt": "Modified stops: %d",
            "apply_changes_button": "Apply Changes",
            "changes_applied_success": "Changes applied successfully.",
            "last_operation_result": "Last Operation Result",
            "json_inspection_request": "JSON Inspection Requested",
            "optimization_in_progress": "Optimization in progress...",
            "encountered_error": "Encountered Error",
            "json_debug_description": "This is the data packet sent to the AI. Useful for debugging '0 suggestions'.",
            "json_detail": "JSON Detail",
            "diagnostics_log": "Diagnostics Log",
            "clear": "Clear",
            "frequency_suggestion_prompt_fmt": "I'm planning the railway schedule for the line \"%@\".\nStops: %@.\nAverage dwell time per stop: 3 minutes.\n\nSuggest an optimal hourly frequency (e.g., every 30 min, every hour) based on route length and service type (Regional/Direct). Provide a concise response with the frequency and a brief rationale.",
            "ai_error_fmt": "Error during AI request: %@",
            "create_track_button": "Create Track",
            "current_path": "Current Path",
            "select_intermediate_station": "Select Intermediate Station",
            "in_line": "In Line",
            "train_label_fmt": "Train: %@",
            "total_delay_label": "Total Delay",
            "detailed_schedule": "Detailed Schedule",
            "dwell_time_short": "Dwell",
            "platform_short": "Pl.",
            "timetable_detail": "Timetable Detail",
            "arrival_short": "A:",
            "departure_short": "D:",
            "solve_conflicts_button": "Solve Conflicts",
            "ai_limit_title": "AI Limit",
            "ai_too_many_trains_fmt": "Too many trains (%d). The maximum limit for AI optimization is 50 trains. Reduce the number of trains and try again.",
            "add_station_upstream": "Add upstream station",
            "add_station_downstream": "Add downstream station",
            "dwell_time_min": "%d min",
            "danger_zone": "Danger Zone",
            "reset_all_data": "Delete All (Network & Trains)",
            "reset_confirm_title": "Confirm Deletion",
            "reset_confirm_message": "Are you sure you want to delete the entire network, all lines, and all trains? This action cannot be undone.",
            "acceleration_val_fmt": "%.2f m/s²",
            "arr_label": "Arr.",
            "arrival_marker": "End of Trip",
            "arrival_time": "Arrival Time",
            "bin_label": "Pl.",
            "code": "Code",
            "color_label": "Color",
            "departure_marker": "Start of Trip",
            "departure_time": "Departure Time",
            "direct_type": "Direct",
            "distance_label": "Distance",
            "edit_stop": "Edit Stop",
            "export_jpeg": "Export JPEG",
            "filter_lines": "Filter Lines",
            "from_label": "From",
            "generating_map": "Generating Map...",
            "generation_desc": "Generation Description",
            "high_speed_type": "High Speed",
            "identification": "Identification",
            "kmh_placeholder": "km/h",
            "line_label_fmt": "Line: %@",
            "lines_visibility": "Lines Visibility",
            "merci_type": "Freight",
            "min_dwell_val": "%d min",
            "network_map": "Network Map",
            "network_schema": "Network Schema",
            "new_track": "New Track",
            "no_line_assigned": "No line assigned",
            "number_label": "Number",
            "numbering_example": "Ex: RE 5001",
            "par_label": "Dep.",
            "planned_arrival": "Planned Arrival",
            "planned_departure": "Planned Departure",
            "planned_timetables": "Planned Timetables",
            "prefix": "Prefix",
            "regional_type": "Regional",
            "reset_zoom": "Reset Zoom",
            "select_station_placeholder": "Select station...",
            "service_stop": "Service Stop",
            "show_all_button": "Show All",
            "sos_label": "Dwell",
            "station_default_name": "New Station",
            "station_label": "Station",
            "station_moving_active": "Station Moving Active",
            "stop_marker": "Stop",
            "support_type": "Support",
            "technical_data": "Technical Data",
            "timetable_itinerary": "Timetable & Itinerary",
            "to_label": "To",
            "track_label": "Track",
            "track_label_short": "Trk",
            "tracks_dwells": "Tracks & Dwells",
            "train_not_found": "Train not found",
            "train_numbering": "Train Numbering",
            "transit_desc": "Transit without stop",
            "transit_marker": "Transit",
            "type_label": "Type",
            "vertical_diagram": "Vertical Diagram",
            "track_occupancy_title": "Track Occupancy: %@",
            "track_label_fmt": "Trk %@",
            "user_management_title": "User Management",
            "error_status": "Error Status",
            "auth_reset_suggestion": "Tip: If the database was reset, perform a new 'Test Login' in Settings to renew the token.",
            "no_users_found": "No users found.",
            "system_users": "System Users",
            "active": "Active",
            "inactive": "Inactive",
            "admin_protected": "Admin protected",
            "new_user_credentials": "New User Credentials",
            "add_user_title": "Add User",
            "min_short": "m",
            "ai_proposals_title": "AI Proposals",
            "ai_proposals_desc_fmt": "Artificial Intelligence has analyzed your network and proposes %d new optimized lines.",
            "select_all": "Select All",
            "deselect_all": "Deselect All",
            "selected_count_fmt": "%d selected",
            "trains_count_fmt": "%d trains",
            "create_sample_trains": "Also create sample trains",
            "create_sample_trains_desc": "Automatically generate cadenced trains for each line (6:00-22:00)",
            "create_lines_btn_fmt": "Create %d Lines",
            "railway_ai_analysis": "RailwayAI Analysis",
            "max_frequency_label": "Max Frequency",
            "recommended_label": "Recommended",
            "optimal_offset_label": "Optimal Offset",
            "routing_constraints": "Line-Dependent Routing",
            "routing_constraints_desc": "Define available tracks for each line and direction.",
            "add_constraint": "Add Routing Constraint",
            "line": "Line",
            "direction": "Direction",
            "allowed_tracks": "Allowed Tracks",
            "allowed_tracks_placeholder": "Ex: 1, 2, 4",
            "all_directions": "All directions",
            "configure": "Configure",
            "no_constraints_defined": "No constraints defined.",
            "cadence_frequency": "Cadence Frequency (min)",
            "propose_ideal_slot": "Propose Ideal Slot",
            "finding_slot": "Finding slot...",
            "suggested_offset_fmt": "Suggested offset: %d min",
            "local_optimization_pignolo": "Local Optimization (Pignolo)",
            "local_ga_searching_desc": "Searching for a free window in current traffic...",
            "missing_api_key_error": "Error: Enter an API KEY in settings (or login to generate one).",
            "optimization_completed": "Optimization Completed",
            "apply_changes": "Apply Changes",
            "optimization_result_message_fmt": "The algorithm reduced conflicts from %d to %d.\nDo you want to apply %d optimized schedules?",
            "optimizing_background_status": "Optimization in progress...",
            "optimizing_step_fmt": "Optimization (Step %d-6)...",
            "capolinea_e_binari": "Terminals and Tracks",
            "simulation": "Simulation",
            "simulation_dashboard": "Traffic Monitoring",
            "simulation_time": "Simulated Time",
            "live_traffic": "Live Traffic",
            "no_active_trains": "No active trains at this time.",
            "en_route_to": "En route to",
            "stopped_at": "Stopped at",
            "moving_label": "Moving",
            "infrastructure_load": "Infrastructure Load",
            "simulation_log": "Simulation Event Log",
            "no_events_yet": "Waiting for events...",
            "controls": "Controls",
            "live_simulation_desc": "Dynamic time management and real-time monitoring.",
            "play": "Play",
            "pause": "Pause",
            "stop_btn": "Stop",
            "confirm_deletion": "Confirm Deletion",
            "read_only_mode": "Read-Only Mode",
            "editing_mode_active": "Editing Mode Active",
            "long_press_to_edit": "Long press for 1 second to enable editing",
            "connection": "Connection",
            "unknown": "Unknown",
            "single_track": "Single Track",
            "double_track": "Double Track",
            "high_speed_track": "High Speed",
            "regional_track": "Regional Line",
            "physical_parameters": "Physical Parameters",
            "connection_to": "Connection: %@",
            "routing_config_hint": "Choose a direction to configure dedicated tracks for the corresponding lines.",
            "no_lines_at_station": "No lines pass through this station.",
            "no_constraints": "No constraints set",
            "coordinates_drag_hint": "Coordinates can also be modified by dragging the station on the map",
            "train_not_found_message": "Train not found",
            "active_conflicts": "Active Conflicts",
            "train_conflicts_count": "This train has %d active conflicts",
            "scheduling_error": "Scheduling Error",
            "vehicle_assignment_required": "Vehicle assignment required",
            "no_vehicle": "No Vehicle",
            "select_vehicle": "Select a vehicle...",
            "vehicle_details": "Vehicle Details",
            "length": "Length",
            "assigned_service": "Assigned Service",
            "back": "Back",
            "tap_map_to_place_station": "Tap on map to place station",
            "station_creation_hint": "Select a point on the map where to create the new station",
            "place_station": "Place Station",
            "confirm_position": "Confirm Position",
            "create_station": "Create Station",
            "position_selected": "Position Selected",
            "coordinates_fmt": "Lat: %.4f, Lon: %.4f",
            "station_details": "Station Details",
            "select_two_stations": "Select Two Stations",
            "track_creation_hint": "Tap two stations on the map to connect them with a track",
            "selected_stations": "Selected Stations",
            "confirm_track": "Confirm Track",
            "create_track": "Create Track",
            "from_station": "From Station",
            "to_station": "To Station",
            "tap_on_map": "Tap on map",
        ]
}
