import Foundation

extension LocalizationManager {
    static let italianDict: [String: String] = [
            "settings": "Impostazioni",
            "language": "Lingua",
            "select_language": "Seleziona Lingua",
            "network": "Infrastruttura",
            "lines": "Relazioni",
            "trains": "Treni",
            "materiale_rotabile": "Materiale Rotabile",
            "railway_ai": "Railway AI",
            "io": "I/O",
            "visualization": "Visualizzazione",
            "diagnostics": "Diagnostica",
            "ai_config": "Configurazione AI",
            "performance": "Performance",
            "global_line_width": "Spessore Linee Globale",
            "global_font_size": "Dimensione Carattere Globale",
            "track_widths": "Spessore Binari",
            "track_single": "Binario Singolo",
            "track_double": "Binario Doppio",
            "track_regional": "Binario Regionale",
            "track_highspeed": "Alta Velocità",
            "train_params": "Parametri Treni",
            "max_speed": "Velocità Max (km/h)",
            "acceleration": "Accelerazione (m/s²)",
            "deceleration": "Decelerazione (m/s²)",
            "priority": "Priorità (1-10)",
            "track_speed_limits": "Limiti Velocità Binari",
            "station": "Stazione",
            "interchange": "Interscambio",
            "depot": "Deposito",
            "junction": "Bivio",
            "export": "Esporta",
            "print": "Stampa",
            "undo": "Annulla",
            "redo": "Ripristina",
            "save": "Salva",
            "delete": "Elimina",
            "edit": "Modifica",
            "add": "Aggiungi",
            "search": "Cerca...",
            "delete_all": "Elimina Tutto",
            "delete_all_confirm_title": "Conferma Eliminazione",
            "delete_all_confirm_message": "Sei sicuro di voler eliminare tutti gli elementi? L'azione non può essere annullata.",
            "stations": "Stazioni",
            "tracks": "Binari",
            "vehicles": "Mezzi",
            "track_display_name": "Binario",
            "station_creation_placeholder": "Creazione Stazione (in sviluppo)",
            "track_creation_placeholder": "Creazione Binario (in sviluppo)",
            "train_creation_placeholder": "Creazione Treno (in sviluppo)",
            "vehicle_creation_placeholder": "Creazione Mezzo (in sviluppo)",
            "name": "Nome",
            "type": "Tipo",
            "capacity": "Capacità",
            "platforms": "Binari",
            "departure": "Partenza",
            "arrival": "Arrivo",
            "dwell_time": "Sosta (min)",
            "track": "Binario",
            "no_trains": "Nessun Treno",
            "no_stations": "Nessuna Stazione",
            "no_lines": "Nessuna Relazione/Rotta",
            "loading": "Caricamento...",
            "error": "Errore",
            "success": "Successo",
            "confirm": "Conferma",
            "file_management": "Gestione File",
            "conflitto_capacita_fmt": "Conflitto tra %@ e %@ a %@. Risorsa: %@ (Capacità: %d). Orario: %@ - %@",
            "instradamento_non_consentito_fmt": "Il treno %@ utilizza un binario non consentito presso %@",
            "save_project": "Salva Progetto",
            "save_infrastructure": "Salvare Infrastruttura",
            "save_infrastructure_desc": "Solo stazioni e binari",
            "import_infrastructure": "Importa Infrastruttura",
            "import_infrastructure_desc": "Solo stazioni e binari (JSON)",
            "open_project": "Apri Progetto",
            "save_local": "Salva Stato Corrente",
            "save_local_desc": "Salvataggio rapido nel database locale",
            "legacy_integration": "Integrazione Legacy",
            "legacy_footer": "Importa file creati con versioni precedenti (FDC 1.x) per convertirli automaticamente al nuovo protocollo Pignolo.",
            "import_old": "Importa Vecchio FDC (.fdc)",
            "export_new": "Esporta Pignolo V2 (.rail)",
            "io_title": "I/O Dati",
            "support_format": "Supporta .rail, .fdc, .json",
            "station_json_import": "Aggiunta Stazioni (JSON)",
            "station_json_import_desc": "Incolla uno snippet di oggetti JSON (anche con commenti) per aggiungere stazioni alla rete.",
            "station_json_placeholder": "{ \"id\": \"NEW_01\", \"name\": \"Stazione\", \"latitude\": 0.0, \"longitude\": 0.0, \"type\": \"station\" }",
            "station_json_add_button": "Aggiungi Stazioni",
            "station_json_empty": "Incolla prima uno snippet JSON valido.",
            "station_json_result_fmt": "Stazioni aggiunte: %d. Saltate: %d.",
            "station_json_error_fmt": "Errore nel JSON: %@",
            "done": "Fine",
            "cancel": "Annulla",
            "show_all": "Mostra Tutte",
            "filter": "Filtra",
            "search_station": "Cerca stazione...",
            "empty_line": "Percorso Vuoto",
            "no_connection": "Nessuna Connessione",
            "show_all_anyway": "Mostra comunque tutte le stazioni",
            "must_create_stations": "Devi prima creare le stazioni dalla sezione 'Rete'.",
            "select_station": "Seleziona Stazione",
            "edit_station": "Modifica Stazione",
            "close": "Chiudi",
            "delete_station": "Elimina Stazione",
            "delete_confirm": "Sei sicuro di voler eliminare questa stazione? L'azione non può essere annullata.",
            "station_data": "Anagrafica",
            "station_name": "Nome Stazione",
            "functional_type": "Tipo Funzionale",
            "standard_station": "Stazione Standard",
            "platform_count": "Numero Binari",
            "hubs_interchanges": "Hub e Interscambi",
            "belongs_to_hub": "Appartiene a HUB",
            "no_hub": "Nessun HUB (Indipendente)",
            "visual_style": "Aspetto Grafico",
            "coordinates": "Coordinate",
            "latitude": "Latitudine",
            "longitude": "Longitudine",
            "move_mode": "Modalità Modifica Posizione",
            "move_mode_on": "MODALITÀ ATTIVA: Puoi trascinare la stazione sulla mappa o digitare le coordinate.",
            "move_mode_off": "MODALITÀ DISATTIVA: La posizione è bloccata per evitare spostamenti accidentali. Abilita la modalità per modificare.",
            "custom_color": "Colore Personalizzato",
            "details": "Dettagli",
            "general_options": "Opzioni Generali",
            "show_grid": "Mostra Griglia",
            "use_cloud_ai": "Risoluzione Conflitti via Cloud AI",
            "sizes": "Dimensioni",
            "line_width_px": "Spessore Linee: %d px",
            "font_size_pt": "Dimensione Font: %d pt",
            "track_widths_map": "Spessore Binari sulla Mappa",
            "track_single_px": "Binario Singolo: %.1f px",
            "track_double_px": "Binario Doppio: %.1f px",
            "track_regional_px": "Binario Regionale: %.1f px",
            "track_highspeed_px": "Binario Alta Velocità: %.1f px",
            "reset_defaults": "Ripristina Valori Predefiniti",
            "map_preview": "Anteprima Mappa",
            "example_station": "STAZIONE ESEMPIO",
            "regional_line": "Relazione Regionale",
            "edge_representation": "Rappresentazione Arco",
            "server_config": "Configurazione Server",
            "api_base_url": "Server API Base URL",
            "restore_default_url": "Ripristina URL di default",
            "username": "Username",
            "password": "Password",
            "permanent_api_key": "API Key Permanente",
            "auth_footer": "Usa la Password per il login temporaneo o l'API Key per l'accesso permanente.",
            "authentication": "Autenticazione",
            "test_login": "Test Login",
            "generate_api_key": "Genera API Key",
            "login_success": "Login Riuscito! Token salvato.",
            "login_error": "Errore Login: %@",
            "api_key_generated": "API Key Generata e Salvata!",
            "api_key_error": "Errore Generazione Key: %@",
            "ai_api_key_auth": "Autenticazione API Key",
            "ai_get_key_instruction": "Per ottenere la tua API Key:",
            "ai_step_1": "1. Vai sulla dashboard di Railway AI",
            "ai_step_2": "2. Effettua il login con le tue credenziali",
            "ai_step_3": "3. Copia la tua API Key dalla dashboard",
            "ai_step_4": "4. Incollala nel campo sopra",
            "ai_open_dashboard": "Apri Railway AI Dashboard",
            "ai_verify_key": "Verifica API Key",
            "ai_key_invalid": "API Key non valida: %@",
            "ai_key_valid_fmt": "✓ API Key valida - Utente: %@ - Scadenza: %d giorni",
            "ai_key_expiring_fmt": "⚠️ Attenzione: La chiave scade tra %d giorni!",
            "diagnostics_and_info": "Diagnostica e Info",
            "show_network_logs": "Mostra Log di Rete",
            "info": "Informazioni",
            "credits_author": "Credits e Autore",
            "debug_data_json": "Debug Dati (JSON)",
            "show_json_lines": "Mostra JSON Linee",
            "show_json_trains": "Mostra JSON Treni",
            "hub_position": "Posizione nell'Hub",
            "hub_standard_pos": "Standard (In Basso a Sx)",
            "hub_logic_description": "Questa stazione è legata logicamente a un'altra. Verrà trattata come punto di interscambio rapido.",
            "track_properties": "Proprietà Binario",
            "distance_km": "Distanza (km)",
            "distance": "Distanza",
            "max_speed_kmh": "Velocità Max (km/h)",
            "speed": "Velocità",
            "track_type": "Tipo Binario",
            "capacity_trains_h": "Capacità (treni/h)",
            "delete_track": "Elimina Binario",
            "edit_track": "Modifica Binario",
            "delete_track_confirm": "Sei sicuro di voler eliminare questo binario? L'azione non può essere annullata.",
            "selection": "Selezione",
            "trains_selected_count": "%d treni selezionati",
            "plus_others_count": "+ altri %d",
            "quick_actions": "Azioni Rapide",
            "shift_time_minutes": "Sposta Orario: %@%d min",
            "apply_shift": "Applica Spostamento",
            "delete_selected": "Elimina Selezionati",
            "batch_edit": "Modifica Multipla",
            "delete_trains": "Elimina Treni",
            "delete_trains_confirm": "Sei sicuro di voler eliminare %d treni? L'azione non è reversibile.",
            "select_category": "Seleziona una categoria",
            "exporting_in_progress": "Esportazione in corso...",
            "current_screen": "Schermata Corrente",
            "export_jpg": "Esporta JPG",
            "export_pdf": "Esporta PDF",
            "map": "Mappa",
            "high_res_map": "Mappa Alta Risoluzione",
            "print_job_map": "Stampa Mappa FdC",
            "stations_count": "Stazioni (%d)",
            "tracks_count": "Binari (%d)",
            "edit_line": "Modifica Relazione",
            "delete_line": "Elimina Relazione",
            "no_trains_assigned": "Nessun treno assegnato a questa relazione.",
            "unassigned_trains": "Treni Non Assegnati",
            "schedule_management": "Gestione Orari",
            "delete_all_trains": "Elimina Tutti i Treni",
            "delete_all_trains_help": "Elimina tutti i treni dal sistema (inclusi i fantasmi)",
            "ai_suggestion_alert": "Suggerimento AI",
            "ok": "Ok",
            "default_train_params": "Parametri Predefiniti Treni",
            "new_train_params_desc": "Questi parametri vengono usati quando crei un nuovo treno",
            "regional_train": "Treno Regionale",
            "intercity_train": "Treno Intercity",
            "highspeed_train": "Treno Alta Velocità",
            "max_speed_label": "Velocità Max:",
            "acceleration_label": "Accelerazione:",
            "deceleration_label": "Decelerazione:",
            "priority_label": "Priorità:",
            "track_speed_limits_section": "Velocità Massime Binari",
            "track_speed_limits_desc": "Limiti di velocità per tipo di binario",
            "train_track_params_title": "Parametri Treni e Binari",
            "path_composition": "Composizione Percorso",
            "line_details": "Dettagli Infrastruttura",
            "line_name_placeholder": "Nome Linea Infrastrutturale",
            "route_name_placeholder": "Nome Rotta (es. Milano-Roma)",
            "code_prefix_placeholder": "Prefisso Codice (es. RE)",
            "number_prefix_placeholder": "Prefisso Numerico",
            "line_color": "Colore Infrastruttura",
            "route_color": "Colore Rotta",
            "new_line": "Nuova Linea Infrastrutturale",
            "new_route": "Nuova Linea",
            "select_stations_hint": "Tocca le stazioni sulla mappa per tracciare il percorso.",
            "confirm_path": "Conferma Percorso",
            "route_details": "Dettagli Linea",
            "route_name": "Nome Linea",
            "save_route": "Salva Linea",
            "line_name_example": "Nome Linea (es. Tirrenica Sud)",
            "number_prefix_example": "Prefisso Numerico (es. 5)",
            "train_details": "Dettagli Treno",
            "number": "Numero",
            "name_optional": "Nome (opzionale)",
            "train_type_picker": "Tipo",
            "departure_picker": "Partenza",
            "selected_line": "Linea Selezionata",
            "stop_sequence": "Sequenza Fermate",
            "select_terminals_desc": "Seleziona i terminal o aggiungi manualmente",
            "add_stop_manual": "Aggiungi fermata manuale",
            "new_trip": "Nuova Corsa",
            "create": "Crea",
            "train_name_default": "Treno %d",
            "freight_train": "Treno Merci",
            "support_train": "Treno Supporto",
            "developed_by": "Sviluppato da",
            "version_label": "Versione %@",
            "project_info_title": "Informazioni sul Progetto",
            "project_description": "FdC Railway Manager è uno strumento avanzato per la gestione, simulazione e ottimizzazione di reti ferroviarie locali. Integra algoritmi di pathfinding, rilevamento conflitti e intelligenza artificiale per garantire orari efficienti e sicuri.",
            "technologies_used": "Tecnologie utilizzate:",
            "reactive_interface": "Interfaccia Reattiva",
            "ml_optimization": "Ottimizzazione via ML",
            "geographic_visualization": "Visualizzazione Geografica",
            "credits": "Credits",
            "no_stations_system": "Non ci sono stazioni registrate nel sistema.",
            "line_no_stations": "Questa relazione non ha ancora stazioni assegnate. Aggiungile nella scheda 'Relazioni'.",
            "no_connected_tracks": "Non ci sono binari che collegano l'ultima stazione scelta ad altri nodi. Disegna un binario o mostra tutte le stazioni.",
            "no_stations_criteria": "Nessuna stazione corrisponde ai criteri di ricerca.",
            "current_project": "Progetto Corrente",
            "unnamed_network": "Rete Senza Nome",
            "stations_count_label": "%d stazioni",
            "tracks_count_label": "%d binari",
            "lines_count_label": "%d relazioni",
            "trains_count_label": "%d treni",
            "trains_count_fmt": "%d treni",
            "last_save": "Ultimo salvataggio: %@",
            "quick_save": "Salvataggio Rapido",
            "save_current_state": "Salva Stato Corrente",
            "auto_save_local_desc": "Salvataggio automatico nel database locale",
            "import_export_files": "Import / Export File",
            "export_project": "Esporta Progetto",
            "save_rail_file_desc": "Salva come file .rail (Pignolo V2)",
            "import_project": "Importa Progetto",
            "support_formats_desc": "Supporta .rail, .fdc, .railml, .json",
            "legacy_formats": "Formati Legacy",
            "legacy_formats_footer": "Importa file creati con versioni precedenti (FDC 1.x) per convertirli automaticamente al nuovo protocollo Pignolo V2.",
            "import_fdc_legacy": "Importa FDC Legacy (.fdc)",
            "import_railml": "Importa RailML (.railml)",
            "import_error_title": "Errore Import",
            "security_scoped_error": "Impossibile ottenere l'accesso al file (Security Scoped Resource)",
            "decode_error": "Impossibile decodificare il file. Formato non riconosciuto.",
            "io_management": "Gestione I/O",
            "smart_scheduling_intel": "Intelligenza di Pianificazione",
            "optimize_button": "Ottimizza",
            "system_status": "Stato Sistema",
            "trains_count": "%d Treni",
            "stations_label": "Stazioni",
            "segments_label": "Tratte",
            "status_label": "Status",
            "waiting_status": "In attesa",
            "optimized_status": "Ottimizzato",
            "proposed_modifications": "Modifiche Proposte",
            "no_modifications_needed": "Nessuna modifica necessaria. Orario ottimale.",
            "optimization_analysis": "Analisi Ottimizzazione",
            "detected_label": "Rilevati",
            "resolved_label": "Risolti",
            "remaining_label": "Rimasti",
            "residual_conflicts_detail": "Dettaglio Conflitti Residui",
            "total_optimized_time": "Tempo Totale Ottimizzato",
            "ready_for_optimization": "Pronto per l'ottimizzazione",
            "ai_welcome_desc": "Carica i treni e clicca su Ottimizza per usare RailwayAI e risolvere tutti i conflitti della rete.",
            "ai_analyzing": "Analisi AI in corso...",
            "platform_at": "Binario %d",
            "modification": "Modifica",
            "impact_label": "Impatto: %ds",
            "trains_to_schedule": "Treni da schedulare",
            "manage_trains": "Gestisci treni",
            "type_speed_label": "Tipo: %@, Velocità max: %d km/h",
            "timetable_traffic_sim": "Simulazione Orari e Traffico",
            "calculate_timetables": "Calcola Orari e Conflitti",
            "calculating_in_progress": "Calcolo in corso...",
            "export_result": "Esporta risultato",
            "view_timetable_chart": "Visualizza grafico orari",
            "local_infrastructure": "Infrastruttura Locale (FDC Engine)",
            "simulate_full_network": "Simula Rete Completa",
            "stops_count_label": "%d fermate",
            "conflict_dashboard": "Dashboard Conflitti",
            "manual_timetable_edit": "Editing manuale orari",
            "edit_timetables_manually": "Modifica orari manualmente",
            "advanced_export_print": "Esportazione avanzata e stampa",
            "copy_to_clipboard": "Copia risultato negli appunti",
            "print_result": "Stampa risultato",
            "file_import": "Importazione file",
            "import_fdc_txt": "Importa file .fdc o .txt",
            "timetables_conflicts_result": "Risultato Orari/Conflitti",
            "detected_conflicts": "Conflitti rilevati",
            "scheduler_title": "Scheduler",
            "import_fdc_button": "Importa .fdc",
            "manage_trains_title": "Gestione Treni",
            "add_train": "Aggiungi treno",
            "new_train": "Nuovo Treno",
            "train_name": "Nome treno",
            "add_button": "Aggiungi",
            "timetable_chart_title": "Grafico Orari Treni",
            "manual_edit_title": "Modifica manuale orari e conflitti",
            "print_preview_title": "Anteprima di stampa",
            "print_job_scheduler": "Orari e conflitti",
            "network_load_error": "Errore durante il caricamento della rete: %@",
            "network_save_error": "Errore durante il salvataggio della rete: %@",
            "single_trip": "Corsa Singola",
            "cadenced_trip": "Cadenzato",
            "even": "Pari",
            "odd": "Dispari",
            "outward": "Andata",
            "return": "Ritorno",
            "genetic_opt_gen_fmt": "Ottimizzazione Genetica (Gen %d)",
            "conflicts_count_fmt": "%d conflitti",
            "cancelling": "Annullamento...",
            "stop": "Interrompi",
            "generate": "Genera",
            "schedule_generation": "Generazione Orari",
            "schedule_gen_line_fmt": "Generazione Orari - Relazione %@",
            "mode": "Modalità",
            "from": "Da",
            "to": "A",
            "via": "Via",
            "path": "Percorso",
            "stations_count_fmt": "%d stazioni",
            "length_short": "Lung.",
            "est_duration_short": "Durata est.",
            "duration_min_fmt": "%.1f min",
            "train_type": "Tipo Treno",
            "start_hour": "Ora Inizio",
            "end_hour": "Ora Fine",
            "interval": "Intervallo",
            "interval_min_fmt": "%d min",
            "every_min_fmt": "Ogni %d min",
            "start_number": "Numero Iniziale",
            "num_placeholder": "Num",
            "parity": "Parità",
            "generate_return_trips": "Genera Corse di Ritorno",
            "trains_to_be_created_fmt": "Verranno creati %d treni.",
            "optimization_ga": "Ottimizzazione (GA)",
            "cloud_ai_active_desc": "Ottimizzazione Cloud AI Attiva (Globale).",
            "local_ga_desc": "L'A.G. locale regolerà partenze e soste per eliminare i conflitti.",
            "path_mode": "Modalità Percorso",
            "method": "Metodo",
            "auto_calculation": "Calcolo Automatico",
            "manual_composition": "Composizione Manuale",
            "define_terminals": "Definisci Terminal",
            "via_passage": "Passaggio per (Via)",
            "add_via_point": "Aggiungi punto di via",
            "invert_path_desc": "Inverti Percorso (B -> A)",
            "calculating_path_desc": "Calcolo percorso in corso...",
            "calculate_proposed_paths": "Calcola Percorsi Proposti",
            "proposed_path": "Percorso Proposto",
            "select_dots": "Seleziona...",
            "path_alt_fmt": "%@ (%d fermate, %.1f km)",
            "path_found_fmt": "Percorso trovato: %@",
            "total_distance": "Distanza totale:",
            "calculated_itinerary": "Itinerario calcolato:",
            "manual_composition_desc": "Utilizza la sezione sottostante per gestire le stazioni della sequenza.",
            "error_index_not_found_fmt": "Errore: Indice non trovato (%d)",
            "unknown_station": "Sconosciuta",
            "error_stations_not_in_line": "Stazioni non trovate nella relazione selezionata.",
            "error_select_terminals": "Seleziona almeno una stazione di partenza e una di arrivo.",
            "error_no_path_found_fmt": "Nessun percorso trovato tra %@ e %@.",
            "multi_line_path": "Percorso Multi-Relazione",
            "error_no_simple_path": "Nessun percorso semplice trovato che colleghi tutte le fermate.",
            "route_analysis": "Analisi rotta...",
            "line_analysis": "Analisi infrastruttura...",
            "starting_pipeline": "Avvio Pipeline 7-Step...",
            "preparation": "Preparazione...",
            "sending_to_cloud": "Inviando al Cloud...",
            "applying": "Applicando...",
            "validation": "Validazione...",
            "final_refinement": "Rifinitura Finale...",
            "optimized": "Ottimizzato!",
            "almost_resolved_fmt": "Quasi risolto (%d rimasti)",
            "filled_star": "Stella piena",
            "filled_square": "Quadrato pieno",
            "empty_square": "Quadrato vuoto",
            "filled_circle": "Cerchio pieno",
            "empty_circle": "Cerchio vuoto",
            "top_left_offset": "In Alto a Sx",
            "top_right_offset": "In Alto a Dx",
            "bottom_left_offset": "In Basso a Sx",
            "bottom_right_offset": "In Basso a Dx",
            "unnamed_line": "Linea Senza Nome",
            "all_tab": "Tutti",
            "hotspots_tab": "Hotspots",
            "lines_tab": "Linee",
            "line_segments": "Tratte Linea",
            "nodes_stations": "Nodi/Stazioni",
            "perfect_timetable": "Piano Orario Perfetto",
            "no_conflicts_desc": "L'algoritmo ha risolto tutti i conflitti. Il piano è pronto per l'esercizio.",
            "conflicts_detected_fmt_short": "%d Conflitti Rilevati",
            "conflict_analysis_desc": "Analisi delle collisioni temporali e risorse sature",
            "criticality": "Criticità",
            "consecutive_collisions": "Collisioni consecutive in questo punto",
            "export_completed": "✅ Export completato",
            "export_error_fmt": "Errore export: %@",
            "import_completed_fmt": "✅ Import completato: %@",
            "import_error_fmt": "Errore caricamento: %@",
            "railml_parsing_failed": "Parsing RailML fallito",
            "loaded_rail_file_fmt": "✅ Caricato file .rail: %@",
            "ai_optimizer_fdc": "Ottimizzatore FDC (v1/v2)",
            "solve_conflicts_json": "Risolvi Conflitti (FDC JSON)",
            "advanced_optimizer_cpp": "Ottimizzatore Avanzato (GA C++)",
            "global_optimization_pignolo": "Ottimizzazione Globale (Pignolo)",
            "conflicts_detected_fmt": "Conflitti rilevati: %d",
            "total_delay_fmt": "Ritardo totale: %.1f min",
            "planning_assistant_fast": "Assistente Pianificazione (Fast Proposer)",
            "target_lines_fmt": "Target Linee: %d",
            "generate_schedule_proposal": "Genera Proposta Orario",
            "review_proposals_fmt": "Rivedi Proposte (%d linee)",
            "optimized_solutions": "Soluzioni Ottimizzate",
            "departure_adj_fmt": "Partenza: %@%.1f min",
            "dwells_extended_fmt": "%d soste allungate",
            "schedules_updated_success": "Piani di viaggio aggiornati correttamente.",
            "apply_schedule_change": "Applica Cambio Orario",
            "proposed_solutions": "Soluzioni Proposte",
            "unknown_train": "Treno Sconosciuto",
            "new_departure_fmt": "Nuova Partenza: %@",
            "modified_stops_fmt": "Soste modificate: %d",
            "apply_changes_button": "Applica Modifiche",
            "changes_applied_success": "Modifiche applicate con successo.",
            "last_operation_result": "Risultato Ultima Operazione",
            "json_inspection_request": "Ispezione JSON Richiesta",
            "optimization_in_progress": "Ottimizzazione in corso...",
            "encountered_error": "Errore Riscontrato",
            "json_debug_description": "Questo è il pacchetto dati inviato all'IA. Utile per il debug dei '0 suggerimenti'.",
            "json_detail": "Dettaglio JSON",
            "diagnostics_log": "Log Diagnostica",
            "clear": "Cancella",
            "frequency_suggestion_prompt_fmt": "Sto pianificando l'orario ferroviario per la linea \"%@\".\nFermate: %@.\nTempo di sosta medio per fermata: 3 minuti.\n\nSuggerisci una frequenza oraria ottimale (es. ogni 30 min, ogni ora) basandoti sulla lunghezza del percorso e sul tipo di servizio (Regionale/Diretto). Fornisci una risposta concisa con la frequenza e una breve motivazione.",
            "ai_error_fmt": "Errore durante la richiesta AI: %@",
            "create_track_button": "Crea Binario",
            "current_path": "Percorso Corrente",
            "select_intermediate_station": "Seleziona Stazione Intermedia",
            "in_line": "Nella Linea",
            "train_label_fmt": "Treno: %@",
            "total_delay_label": "Totale Ritardo",
            "detailed_schedule": "Orario Dettagliato",
            "dwell_time_short": "Sosta",
            "platform_short": "Bin.",
            "timetable_detail": "Dettaglio Orario",
            "arrival_short": "A:",
            "departure_short": "P:",
            "solve_conflicts_button": "Risolvi Conflitti",
            "ai_limit_title": "Limite AI",
            "ai_too_many_trains_fmt": "Troppi treni (%d). Il limite massimo per l'ottimizzazione AI è 50 treni. Riduci il numero di treni e riprova.",
            "add_station_upstream": "Aggiungi stazione a monte",
            "add_station_downstream": "Aggiungi stazione a valle",
            "dwell_time_min": "%d min",
            "danger_zone": "Zona Pericolo",
            "reset_all_data": "Elimina Tutto (Rete e Treni)",
            "reset_confirm_title": "Conferma Eliminazione",
            "reset_confirm_message": "Sei sicuro di voler eliminare l'intera rete, tutte le linee e tutti i treni? Questa azione non può essere annullata.",
            "acceleration_val_fmt": "%.2f m/s²",
            "arr_label": "Arr.",
            "arrival_marker": "Fine Corsa",
            "arrival_time": "Orario Arrivo",
            "bin_label": "Bin.",
            "code": "Codice",
            "color_label": "Colore",
            "departure_marker": "Inizio Corsa",
            "departure_time": "Orario Partenza",
            "direct_type": "Diretto",
            "distance_label": "Distanza",
            "edit_stop": "Modifica Fermata",
            "export_jpeg": "Esporta JPEG",
            "filter_lines": "Filtra Linee",
            "from_label": "Da",
            "generating_map": "Generazione Mappa...",
            "generation_desc": "Descrizione Generazione",
            "high_speed_type": "Alta Velocità",
            "identification": "Identificazione",
            "kmh_placeholder": "km/h",
            "line_label_fmt": "Linea: %@",
            "lines_visibility": "Visibilità Linee",
            "merci_type": "Merci",
            "min_dwell_val": "%d min",
            "network_map": "Mappa Rete",
            "network_schema": "Schema Rete",
            "new_track": "Nuovo Binario",
            "no_line_assigned": "Nessuna relazione assegnata",
            "number_label": "Numero",
            "numbering_example": "Es: RE 5001",
            "par_label": "Par.",
            "planned_arrival": "Arrivo Programmato",
            "planned_departure": "Partenza Programmata",
            "planned_timetables": "Orari Programmati",
            "prefix": "Prefisso",
            "regional_type": "Regionale",
            "reset_zoom": "Resetta Zoom",
            "select_station_placeholder": "Seleziona stazione...",
            "service_stop": "Fermata Servizio",
            "show_all_button": "Mostra Tutto",
            "sos_label": "Sos.",
            "station_default_name": "Nuova Stazione",
            "station_label": "Stazione",
            "station_moving_active": "Spostamento Stazione Attivo",
            "stop_marker": "Fermata",
            "support_type": "Supporto",
            "technical_data": "Dati Tecnici",
            "timetable_itinerary": "Orario e Itinerario",
            "to_label": "A",
            "track_label": "Binario",
            "track_label_short": "Bin",
            "tracks_dwells": "Binari e Soste",
            "train_not_found": "Treno non trovato",
            "train_numbering": "Numerazione Treni",
            "transit_desc": "Transito senza sosta",
            "transit_marker": "Transito",
            "type_label": "Tipo",
            "vertical_diagram": "Diagramma Verticale",
            "track_occupancy_title": "Occupazione Binari: %@",
            "track_label_fmt": "Bin %@",
            "user_management_title": "Gestione Utenti",
            "error_status": "Stato Errore",
            "auth_reset_suggestion": "Suggerimento: Se il database è stato resettato, effettua un nuovo 'Test Login' nelle Impostazioni per rinnovare il token.",
            "no_users_found": "Nessun utente trovato.",
            "system_users": "Utenti di Sistema",
            "active": "Attivo",
            "inactive": "Inattivo",
            "admin_protected": "Admin protetto",
            "new_user_credentials": "Credenziali Nuovo Utente",
            "add_user_title": "Aggiungi Utente",
            "min_short": "m",
            "ai_proposals_title": "Proposte AI",
            "ai_proposals_desc_fmt": "L'intelligenza artificiale ha analizzato la tua rete e propone %d nuove linee ottimizzate.",
            "select_all": "Seleziona Tutte",
            "deselect_all": "Deseleziona Tutte",
            "selected_count_fmt": "%d selezionate",
            "create_sample_trains": "Crea anche treni di esempio",
            "create_sample_trains_desc": "Genera automaticamente treni cadenzati per ogni linea (6:00-22:00)",
            "create_lines_btn_fmt": "Crea %d Linee",
            "railway_ai_analysis": "RailwayAI Analysis",
            "max_frequency_label": "Frequenza Max",
            "recommended_label": "Consigliata",
            "optimal_offset_label": "Offset Ottimale",
            "routing_constraints": "Instradamento per Linea",
            "routing_constraints_desc": "Definisci i binari utilizzabili per ciascuna linea e direzione.",
            "add_constraint": "Aggiungi Vincolo Instradamento",
            "line": "Linea",
            "direction": "Direzione",
            "allowed_tracks": "Binari Consentiti",
            "allowed_tracks_placeholder": "Es: 1, 2, 4",
            "all_directions": "Tutte le direzioni",
            "configure": "Configura",
            "no_constraints_defined": "Nessun vincolo definito.",
            "cadence_frequency": "Frequenza Cadenzamento (min)",
            "propose_ideal_slot": "Proponi Slot Ideale",
            "finding_slot": "Ricerca slot...",
            "suggested_offset_fmt": "Offset suggerito: %d min",
            "local_optimization_pignolo": "Ottimizzazione Locale (Pignolo)",
            "local_ga_searching_desc": "Ricerca di un intervallo libero nel traffico attuale...",
            "missing_api_key_error": "Errore: Inserisci una API KEY nelle impostazioni (o fai il login per generarne una).",
            "optimization_completed": "Ottimizzazione Completata",
            "apply_changes": "Applica Modifiche",
            "optimization_result_message_fmt": "L'algoritmo ha ridotto i conflitti da %d a %d.\nVuoi applicare %d orari ottimizzati?",
            "optimizing_step_fmt": "Ottimizzazione (Step %d-6)...",
            "capolinea_e_binari": "Capolinea e Binari",
            "simulation": "Simulazione",
            "simulation_dashboard": "Monitoraggio Traffico",
            "simulation_time": "Tempo Simulato",
            "live_traffic": "Traffico Live",
            "no_active_trains": "Nessun treno attivo in questo momento.",
            "en_route_to": "In viaggio verso",
            "stopped_at": "Fermo a",
            "moving_label": "In movimento",
            "infrastructure_load": "Carico Infrastruttura",
            "simulation_log": "Log Eventi Simulazione",
            "no_events_yet": "In attesa di eventi...",
            "controls": "Controlli",
            "live_simulation_desc": "Gestione dinamica del tempo e monitoraggio real-time.",
            "play": "Avvia",
            "pause": "Pausa",
            "stop_btn": "Ferma",
            "confirm_deletion": "Conferma Eliminazione",
            "read_only_mode": "Modalità Sola Lettura",
            "editing_mode_active": "Modalità Modifica Attiva",
            "long_press_to_edit": "Tieni premuto per 1 secondo per abilitare le modifiche",
            "connection": "Collegamento",
            "unknown": "Sconosciuto",
            "single_track": "Binario Singolo",
            "double_track": "Doppio Binario",
            "high_speed_track": "Alta Velocità",
            "regional_track": "Linea Regionale",
            "physical_parameters": "Parametri Fisici",
            "connection_to": "Collegamento: %@",
            "routing_config_hint": "Scegli una direzione per configurare i binari dedicati alle linee corrispondenti.",
            "no_lines_at_station": "Nessuna linea attraversa questa stazione.",
            "no_constraints": "Nessun vincolo impostato",
            "coordinates_drag_hint": "Le coordinate possono essere modificate anche trascinando la stazione sulla mappa",
            "train_not_found_message": "Treno non trovato",
            "active_conflicts": "Conflitti Attivi",
            "train_conflicts_count": "Il treno ha %d conflitti attivi",
            "scheduling_error": "Errore Calcolo Orario",
            "vehicle_assignment_required": "Assegnazione materiale rotabile obbligatoria",
            "no_vehicle": "Nessun Mezzo",
            "select_vehicle": "Seleziona un mezzo...",
            "vehicle_details": "Scheda Materiale Rotabile",
            "length": "Lunghezza",
            "assigned_service": "Servizio Assegnato",
            "back": "Indietro",
            "tap_map_to_place_station": "Tocca sulla mappa per posizionare la stazione",
            "station_creation_hint": "Seleziona un punto sulla mappa dove creare la nuova stazione",
            "place_station": "Posiziona Stazione",
            "confirm_position": "Conferma Posizione",
            "create_station": "Crea Stazione",
            "position_selected": "Posizione Selezionata",
            "coordinates_fmt": "Lat: %.4f, Lon: %.4f",
            "station_details": "Dettagli Stazione",
            "select_two_stations": "Seleziona Due Stazioni",
            "track_creation_hint": "Tocca due stazioni sulla mappa per collegarle con un binario",
            "selected_stations": "Stazioni Selezionate",
            "confirm_track": "Conferma Binario",
            "create_track": "Crea Binario",
            "from_station": "Stazione di Partenza",
            "to_station": "Stazione di Arrivo",
            "tap_on_map": "Tocca sulla mappa",
            "basic_info": "Informazioni di Base",
            "route_path": "Percorso Infrastrutturale",
            "actions": "Azioni",
            "delete_ferrovia": "Elimina Ferrovia",
            "ferrovia_name_placeholder": "Es: Tirrenica Sud",
            "propagate_electrification": "Propaga Elettrificazione",
            "propagate_electrification_description": "Applica il tipo di elettrificazione della linea a tutti i nodi e binari che la compongono.",
            "propagate_electrification_help": "Utile per aggiornare rapidamente l'intera tratta",
            "no_stations_in_ferrovia": "Nessuna stazione assegnata a questa ferrovia.",
    ]
}
