import Foundation
import SwiftUI
import Combine

enum AppLanguage: String, CaseIterable, Identifiable, Codable {
    case italian = "it"
    case english = "en"
    
    var id: String { self.rawValue }
    
    var displayName: String {
        switch self {
        case .italian: return "Italiano"
        case .english: return "English"
        }
    }
}

class LocalizationManager: ObservableObject {
    static let shared = LocalizationManager()
    
    @Published var currentLanguage: AppLanguage {
        didSet {
            UserDefaults.standard.set(currentLanguage.rawValue, forKey: "app_language")
        }
    }
    
    private init() {
        let stored = UserDefaults.standard.string(forKey: "app_language") ?? "it"
        self.currentLanguage = AppLanguage(rawValue: stored) ?? .italian
    }
    
    func string(for key: String) -> String {
        return Self.string(for: key, language: currentLanguage)
    }
    
    static func string(for key: String, language: AppLanguage) -> String {
        let dict = translations[language] ?? translations[.italian]!
        return dict[key] ?? key
    }
    
    static let translations: [AppLanguage: [String: String]] = [
        .italian: [
            "settings": "Impostazioni",
            "language": "Lingua",
            "select_language": "Seleziona Lingua",
            "network": "Rete",
            "lines": "Linee",
            "trains": "Treni",
            "railway_ai": "Railway AI",
            "io": "I/O",
            "visualization": "Visualizzazione",
            "diagnostics": "Diagnostica",
            "ai_config": "Configurazione AI",
            "performance": "Performance",
            "global_line_width": "Spessore Linee Globale",
            "global_font_size": "Dimensione Carattere Globale",
            "track_widths": "Spessore Binari",
            "track_single": "Binario Singolo",
            "track_double": "Binario Doppio",
            "track_regional": "Binario Regionale",
            "track_highspeed": "Alta Velocità",
            "train_params": "Parametri Treni",
            "max_speed": "Velocità Max (km/h)",
            "acceleration": "Accelerazione (m/s²)",
            "deceleration": "Decelerazione (m/s²)",
            "priority": "Priorità (1-10)",
            "track_speed_limits": "Limiti Velocità Binari",
            "station": "Stazione",
            "interchange": "Interscambio",
            "depot": "Deposito",
            "junction": "Bivio",
            "export": "Esporta",
            "print": "Stampa",
            "undo": "Annulla",
            "redo": "Ripristina",
            "save": "Salva",
            "delete": "Elimina",
            "edit": "Modifica",
            "add": "Aggiungi",
            "search": "Cerca...",
            "name": "Nome",
            "type": "Tipo",
            "capacity": "Capacità",
            "platforms": "Binari",
            "departure": "Partenza",
            "arrival": "Arrivo",
            "dwell_time": "Sosta (min)",
            "track": "Binario",
            "no_trains": "Nessun Treno",
            "no_stations": "Nessuna Stazione",
            "no_lines": "Nessuna Linea",
            "loading": "Caricamento...",
            "error": "Errore",
            "success": "Successo",
            "confirm": "Conferma",
            "file_management": "Gestione File",
            "save_project": "Salva Progetto",
            "open_project": "Apri Progetto",
            "save_local": "Salva Stato Corrente",
            "save_local_desc": "Salvataggio rapido nel database locale",
            "legacy_integration": "Integrazione Legacy",
            "legacy_footer": "Importa file creati con versioni precedenti (FDC 1.x) per convertirli automaticamente al nuovo protocollo Pignolo.",
            "import_old": "Importa Vecchio FDC (.fdc)",
            "export_new": "Esporta Pignolo V2 (.rail)",
            "io_title": "I/O Dati",
            "support_format": "Supporta .rail, .fdc, .json",
            "done": "Fine",
            "cancel": "Annulla",
            "show_all": "Mostra Tutte",
            "filter": "Filtra",
            "search_station": "Cerca stazione...",
            "empty_line": "Linea Vuota",
            "no_connection": "Nessuna Connessione",
            "show_all_anyway": "Mostra comunque tutte le stazioni",
            "must_create_stations": "Devi prima creare le stazioni dalla sezione 'Rete'.",
            "select_station": "Seleziona Stazione",
            "edit_station": "Modifica Stazione",
            "close": "Chiudi",
            "delete_station": "Elimina Stazione",
            "delete_confirm": "Sei sicuro di voler eliminare questa stazione? L'azione non può essere annullata.",
            "station_data": "Anagrafica",
            "station_name": "Nome Stazione",
            "functional_type": "Tipo Funzionale",
            "standard_station": "Stazione Standard",
            "platform_count": "Numero Binari",
            "hubs_interchanges": "Hub e Interscambi",
            "belongs_to_hub": "Appartiene a HUB",
            "no_hub": "Nessun HUB (Indipendente)",
            "visual_style": "Aspetto Grafico",
            "coordinates": "Coordinate",
            "latitude": "Latitudine",
            "longitude": "Longitudine",
            "move_mode": "Modalità Modifica Posizione",
            "move_mode_on": "MODALITÀ ATTIVA: Puoi trascinare la stazione sulla mappa o digitare le coordinate.",
            "move_mode_off": "MODALITÀ DISATTIVA: La posizione è bloccata per evitare spostamenti accidentali. Abilita la modalità per modificare.",
            "custom_color": "Colore Personalizzato",
            "details": "Dettagli",
            "general_options": "Opzioni Generali",
            "show_grid": "Mostra Griglia",
            "use_cloud_ai": "Risoluzione Conflitti via Cloud AI",
            "sizes": "Dimensioni",
            "line_width_px": "Spessore Linee: %d px",
            "font_size_pt": "Dimensione Font: %d pt",
            "track_widths_map": "Spessore Binari sulla Mappa",
            "track_single_px": "Binario Singolo: %.1f px",
            "track_double_px": "Binario Doppio: %.1f px",
            "track_regional_px": "Binario Regionale: %.1f px",
            "track_highspeed_px": "Binario Alta Velocità: %.1f px",
            "reset_defaults": "Ripristina Valori Predefiniti",
            "map_preview": "Anteprima Mappa",
            "example_station": "STAZIONE ESEMPIO",
            "regional_line": "Linea Regionale",
            "edge_representation": "Rappresentazione Arco",
            "server_config": "Configurazione Server",
            "api_base_url": "Server API Base URL",
            "restore_default_url": "Ripristina URL di default",
            "username": "Username",
            "password": "Password",
            "permanent_api_key": "API Key Permanente",
            "auth_footer": "Usa la Password per il login temporaneo o l'API Key per l'accesso permanente.",
            "authentication": "Autenticazione",
            "test_login": "Test Login",
            "generate_api_key": "Genera API Key",
            "login_success": "Login Riuscito! Token salvato.",
            "login_error": "Errore Login: %@",
            "api_key_generated": "API Key Generata e Salvata!",
            "api_key_error": "Errore Generazione Key: %@",
            "ai_api_key_auth": "Autenticazione API Key",
            "ai_get_key_instruction": "Per ottenere la tua API Key:",
            "ai_step_1": "1. Vai sulla dashboard di Railway AI",
            "ai_step_2": "2. Effettua il login con le tue credenziali",
            "ai_step_3": "3. Copia la tua API Key dalla dashboard",
            "ai_step_4": "4. Incollala nel campo sopra",
            "ai_open_dashboard": "Apri Railway AI Dashboard",
            "ai_verify_key": "Verifica API Key",
            "ai_key_invalid": "API Key non valida: %@",
            "ai_key_valid_fmt": "✓ API Key valida - Utente: %@ - Scadenza: %d giorni",
            "ai_key_expiring_fmt": "⚠️ Attenzione: La chiave scade tra %d giorni!",
            "diagnostics_and_info": "Diagnostica e Info",
            "show_network_logs": "Mostra Log di Rete",
            "info": "Informazioni",
            "credits_author": "Credits e Autore",
            "debug_data_json": "Debug Dati (JSON)",
            "show_json_lines": "Mostra JSON Linee",
            "show_json_trains": "Mostra JSON Treni",
            "hub_position": "Posizione nell'Hub",
            "hub_standard_pos": "Standard (In Basso a Sx)",
            "hub_logic_description": "Questa stazione è legata logicamente a un'altra. Verrà trattata come punto di interscambio rapido.",
            "track_properties": "Proprietà Binario",
            "distance_km": "Distanza (km)",
            "distance": "Distanza",
            "max_speed_kmh": "Velocità Max (km/h)",
            "speed": "Velocità",
            "track_type": "Tipo Binario",
            "capacity_trains_h": "Capacità (treni/h)",
            "delete_track": "Elimina Binario",
            "edit_track": "Modifica Binario",
            "delete_track_confirm": "Sei sicuro di voler eliminare questo binario? L'azione non può essere annullata.",
            "selection": "Selezione",
            "trains_selected_count": "%d treni selezionati",
            "plus_others_count": "+ altri %d",
            "quick_actions": "Azioni Rapide",
            "shift_time_minutes": "Sposta Orario: %@%d min",
            "apply_shift": "Applica Spostamento",
            "delete_selected": "Elimina Selezionati",
            "batch_edit": "Modifica Multipla",
            "delete_trains": "Elimina Treni",
            "delete_trains_confirm": "Sei sicuro di voler eliminare %d treni? L'azione non è reversibile.",
            "select_category": "Seleziona una categoria",
            "exporting_in_progress": "Esportazione in corso...",
            "current_screen": "Schermata Corrente",
            "export_jpg": "Esporta JPG",
            "export_pdf": "Esporta PDF",
            "map": "Mappa",
            "high_res_map": "Mappa Alta Risoluzione",
            "print_job_map": "Stampa Mappa FdC",
            "stations": "Stazioni",
            "tracks": "Binari",
            "stations_count": "Stazioni (%d)",
            "tracks_count": "Binari (%d)",
            "edit_line": "Modifica Linea",
            "delete_line": "Elimina Linea",
            "no_trains_assigned": "Nessun treno assegnato a questa linea.",
            "unassigned_trains": "Treni Non Assegnati",
            "schedule_management": "Gestione Orari",
            "delete_all_trains": "Elimina Tutti i Treni",
            "delete_all_trains_help": "Elimina tutti i treni dal sistema (inclusi i fantasmi)",
            "ai_suggestion_alert": "Suggerimento AI",
            "ok": "Ok",
            "default_train_params": "Parametri Predefiniti Treni",
            "new_train_params_desc": "Questi parametri vengono usati quando crei un nuovo treno",
            "regional_train": "Treno Regionale",
            "intercity_train": "Treno Intercity",
            "highspeed_train": "Treno Alta Velocità",
            "max_speed_label": "Velocità Max:",
            "acceleration_label": "Accelerazione:",
            "deceleration_label": "Decelerazione:",
            "priority_label": "Priorità:",
            "track_speed_limits_section": "Velocità Massime Binari",
            "track_speed_limits_desc": "Limiti di velocità per tipo di binario",
            "train_track_params_title": "Parametri Treni e Binari",
            "path_composition": "Composizione Percorso",
            "line_details": "Dettagli Linea",
            "line_name_placeholder": "Nome Linea",
            "code_prefix_placeholder": "Prefisso Codice (es. RE)",
            "number_prefix_placeholder": "Prefisso Numerico",
            "line_color": "Colore Linea",
            "new_line": "Nuova Linea",
            "line_name_example": "Nome Linea (es. Milano-Roma)",
            "number_prefix_example": "Prefisso Numerico (es. 5)",
            "train_details": "Dettagli Treno",
            "number": "Numero",
            "name_optional": "Nome (opzionale)",
            "train_type_picker": "Tipo",
            "departure_picker": "Partenza",
            "selected_line": "Linea Selezionata",
            "stop_sequence": "Sequenza Fermate",
            "select_terminals_desc": "Seleziona i terminal o aggiungi manualmente",
            "add_stop_manual": "Aggiungi fermata manuale",
            "new_trip": "Nuova Corsa",
            "create": "Crea",
            "train_name_default": "Treno %d",
            "freight_train": "Treno Merci",
            "support_train": "Treno Supporto",
            "developed_by": "Sviluppato da",
            "version_label": "Versione %@",
            "project_info_title": "Informazioni sul Progetto",
            "project_description": "FdC Railway Manager è uno strumento avanzato per la gestione, simulazione e ottimizzazione di reti ferroviarie locali. Integra algoritmi di pathfinding, rilevamento conflitti e intelligenza artificiale per garantire orari efficienti e sicuri.",
            "technologies_used": "Tecnologie utilizzate:",
            "reactive_interface": "Interfaccia Reattiva",
            "ml_optimization": "Ottimizzazione via ML",
            "geographic_visualization": "Visualizzazione Geografica",
            "credits": "Credits",
            "no_stations_system": "Non ci sono stazioni registrate nel sistema.",
            "line_no_stations": "Questa linea ferroviaria non ha ancora stazioni assegnate. Aggiungile nella scheda 'Linee'.",
            "no_connected_tracks": "Non ci sono binari che collegano l'ultima stazione scelta ad altri nodi. Disegna un binario o mostra tutte le stazioni.",
            "no_stations_criteria": "Nessuna stazione corrisponde ai criteri di ricerca.",
            "current_project": "Progetto Corrente",
            "unnamed_network": "Rete Senza Nome",
            "stations_count_label": "%d stazioni",
            "tracks_count_label": "%d binari",
            "lines_count_label": "%d linee",
            "trains_count_label": "%d treni",
            "last_save": "Ultimo salvataggio: %@",
            "quick_save": "Salvataggio Rapido",
            "save_current_state": "Salva Stato Corrente",
            "auto_save_local_desc": "Salvataggio automatico nel database locale",
            "import_export_files": "Import / Export File",
            "export_project": "Esporta Progetto",
            "save_rail_file_desc": "Salva come file .rail (Pignolo V2)",
            "import_project": "Importa Progetto",
            "support_formats_desc": "Supporta .rail, .fdc, .railml, .json",
            "legacy_formats": "Formati Legacy",
            "legacy_formats_footer": "Importa file creati con versioni precedenti (FDC 1.x) per convertirli automaticamente al nuovo protocollo Pignolo V2.",
            "import_fdc_legacy": "Importa FDC Legacy (.fdc)",
            "import_railml": "Importa RailML (.railml)",
            "import_error_title": "Errore Import",
            "security_scoped_error": "Impossibile ottenere l'accesso al file (Security Scoped Resource)",
            "decode_error": "Impossibile decodificare il file. Formato non riconosciuto.",
            "io_management": "Gestione I/O",
            "smart_scheduling_intel": "Intelligenza di Pianificazione",
            "optimize_button": "Ottimizza",
            "system_status": "Stato Sistema",
            "trains_count": "%d Treni",
            "stations_label": "Stazioni",
            "segments_label": "Tratte",
            "status_label": "Status",
            "waiting_status": "In attesa",
            "optimized_status": "Ottimizzato",
            "proposed_modifications": "Modifiche Proposte",
            "no_modifications_needed": "Nessuna modifica necessaria. Orario ottimale.",
            "optimization_analysis": "Analisi Ottimizzazione",
            "detected_label": "Rilevati",
            "resolved_label": "Risolti",
            "remaining_label": "Rimasti",
            "residual_conflicts_detail": "Dettaglio Conflitti Residui",
            "total_optimized_time": "Tempo Totale Ottimizzato",
            "ready_for_optimization": "Pronto per l'ottimizzazione",
            "ai_welcome_desc": "Carica i treni e clicca su Ottimizza per usare RailwayAI e risolvere tutti i conflitti della rete.",
            "ai_analyzing": "Analisi AI in corso...",
            "platform_at": "Binario %d",
            "modification": "Modifica",
            "impact_label": "Impatto: %ds",
            "trains_to_schedule": "Treni da schedulare",
            "manage_trains": "Gestisci treni",
            "type_speed_label": "Tipo: %@, Velocità max: %d km/h",
            "timetable_traffic_sim": "Simulazione Orari e Traffico",
            "calculate_timetables": "Calcola Orari e Conflitti",
            "calculating_in_progress": "Calcolo in corso...",
            "export_result": "Esporta risultato",
            "view_timetable_chart": "Visualizza grafico orari",
            "local_infrastructure": "Infrastruttura Locale (FDC Engine)",
            "simulate_full_network": "Simula Rete Completa",
            "stops_count_label": "%d fermate",
            "conflict_dashboard": "Dashboard Conflitti",
            "manual_timetable_edit": "Editing manuale orari",
            "edit_timetables_manually": "Modifica orari manualmente",
            "advanced_export_print": "Esportazione avanzata e stampa",
            "copy_to_clipboard": "Copia risultato negli appunti",
            "print_result": "Stampa risultato",
            "file_import": "Importazione file",
            "import_fdc_txt": "Importa file .fdc o .txt",
            "timetables_conflicts_result": "Risultato Orari/Conflitti",
            "detected_conflicts": "Conflitti rilevati",
            "scheduler_title": "Scheduler",
            "import_fdc_button": "Importa .fdc",
            "manage_trains_title": "Gestione Treni",
            "add_train": "Aggiungi treno",
            "new_train": "Nuovo Treno",
            "train_name": "Nome treno",
            "add_button": "Aggiungi",
            "timetable_chart_title": "Grafico Orari Treni",
            "manual_edit_title": "Modifica manuale orari e conflitti",
            "print_preview_title": "Anteprima di stampa",
            "print_job_scheduler": "Orari e conflitti",
            "network_load_error": "Errore durante il caricamento della rete: %@",
            "network_save_error": "Errore durante il salvataggio della rete: %@",
            "single_trip": "Corsa Singola",
            "cadenced_trip": "Cadenzato",
            "even": "Pari",
            "odd": "Dispari",
            "outward": "Andata",
            "return": "Ritorno",
            "genetic_opt_gen_fmt": "Ottimizzazione Genetica (Gen %d)",
            "conflicts_count_fmt": "%d conflitti",
            "cancelling": "Annullamento...",
            "stop": "Interrompi",
            "generate": "Genera",
            "schedule_generation": "Generazione Orari",
            "schedule_gen_line_fmt": "Generazione Orari - Linea %@",
            "mode": "Modalità",
            "from": "Da",
            "to": "A",
            "via": "Via",
            "path": "Percorso",
            "stations_count_fmt": "%d stazioni",
            "length_short": "Lung.",
            "est_duration_short": "Durata est.",
            "duration_min_fmt": "%d min",
            "train_type": "Tipo Treno",
            "start_hour": "Ora Inizio",
            "end_hour": "Ora Fine",
            "interval": "Intervallo",
            "interval_min_fmt": "%d min",
            "start_number": "Numero Iniziale",
            "num_placeholder": "Num",
            "parity": "Parità",
            "trains_to_be_created_fmt": "Verranno creati %d treni.",
            "optimization_ga": "Ottimizzazione (GA)",
            "cloud_ai_active_desc": "Ottimizzazione Cloud AI Attiva (Globale).",
            "local_ga_desc": "L'A.G. locale regolerà partenze e soste per eliminare i conflitti.",
            "path_mode": "Modalità Percorso",
            "method": "Metodo",
            "auto_calculation": "Calcolo Automatico",
            "manual_composition": "Composizione Manuale",
            "define_terminals": "Definisci Terminal",
            "via_passage": "Passaggio per (Via)",
            "add_via_point": "Aggiungi punto di via",
            "invert_path_desc": "Inverti Percorso (B -> A)",
            "calculating_path_desc": "Calcolo percorso in corso...",
            "calculate_proposed_paths": "Calcola Percorsi Proposti",
            "proposed_path": "Percorso Proposto",
            "select_dots": "Seleziona...",
            "path_alt_fmt": "%@ (%d fermate, %.1f km)",
            "path_found_fmt": "Percorso trovato: %@",
            "total_distance": "Distanza totale:",
            "calculated_itinerary": "Itinerario calcolato:",
            "manual_composition_desc": "Utilizza la sezione sottostante per gestire le stazioni della sequenza.",
            "error_index_not_found_fmt": "Errore: Indice non trovato (%d)",
            "unknown_station": "Sconosciuta",
            "error_stations_not_in_line": "Stazioni non trovate nella linea selezionata.",
            "error_select_terminals": "Seleziona almeno una stazione di partenza e una di arrivo.",
            "error_no_path_found_fmt": "Nessun percorso trovato tra %@ e %@.",
            "multi_line_path": "Percorso Multilinee",
            "error_no_simple_path": "Nessun percorso semplice trovato che colleghi tutte le fermate.",
            "line_analysis": "Analisi linea...",
            "starting_pipeline": "Avvio Pipeline 7-Step...",
            "preparation": "Preparazione...",
            "sending_to_cloud": "Inviando al Cloud...",
            "applying": "Applicando...",
            "validation": "Validazione...",
            "final_refinement": "Rifinitura Finale...",
            "optimized": "Ottimizzato!",
            "almost_resolved_fmt": "Quasi risolto (%d rimasti)",
            "filled_star": "Stella piena",
            "filled_square": "Quadrato pieno",
            "empty_square": "Quadrato vuoto",
            "filled_circle": "Cerchio pieno",
            "empty_circle": "Cerchio vuoto",
            "top_left_offset": "In Alto a Sx",
            "top_right_offset": "In Alto a Dx",
            "bottom_left_offset": "In Basso a Sx",
            "bottom_right_offset": "In Basso a Dx",
            "unnamed_line": "Linea Senza Nome",
            "all_tab": "Tutti",
            "hotspots_tab": "Hotspots",
            "lines_tab": "Linee",
            "line_segments": "Tratte Linea",
            "nodes_stations": "Nodi/Stazioni",
            "perfect_timetable": "Piano Orario Perfetto",
            "no_conflicts_desc": "L'algoritmo ha risolto tutti i conflitti. Il piano è pronto per l'esercizio.",
            "conflicts_detected_fmt_short": "%d Conflitti Rilevati",
            "conflict_analysis_desc": "Analisi delle collisioni temporali e risorse sature",
            "criticality": "Criticità",
            "consecutive_collisions": "Collisioni consecutive in questo punto",
            "export_completed": "✅ Export completato",
            "export_error_fmt": "Errore export: %@",
            "import_completed_fmt": "✅ Import completato: %@",
            "import_error_fmt": "Errore caricamento: %@",
            "railml_parsing_failed": "Parsing RailML fallito",
            "loaded_rail_file_fmt": "✅ Caricato file .rail: %@",
            "ai_optimizer_fdc": "Ottimizzatore FDC (v1/v2)",
            "solve_conflicts_json": "Risolvi Conflitti (FDC JSON)",
            "advanced_optimizer_cpp": "Ottimizzatore Avanzato (GA C++)",
            "global_optimization_pignolo": "Ottimizzazione Globale (Pignolo)",
            "conflicts_detected_fmt": "Conflitti rilevati: %d",
            "total_delay_fmt": "Ritardo totale: %.1f min",
            "planning_assistant_fast": "Assistente Pianificazione (Fast Proposer)",
            "target_lines_fmt": "Target Linee: %d",
            "generate_schedule_proposal": "Genera Proposta Orario",
            "review_proposals_fmt": "Rivedi Proposte (%d linee)",
            "optimized_solutions": "Soluzioni Ottimizzate",
            "departure_adj_fmt": "Partenza: %@%.1f min",
            "dwells_extended_fmt": "%d soste allungate",
            "schedules_updated_success": "Piani di viaggio aggiornati correttamente.",
            "apply_schedule_change": "Applica Cambio Orario",
            "proposed_solutions": "Soluzioni Proposte",
            "unknown_train": "Treno Sconosciuto",
            "new_departure_fmt": "Nuova Partenza: %@",
            "modified_stops_fmt": "Soste modificate: %d",
            "apply_changes_button": "Applica Modifiche",
            "changes_applied_success": "Modifiche applicate con successo.",
            "last_operation_result": "Risultato Ultima Operazione",
            "json_inspection_request": "Ispezione JSON Richiesta",
            "optimization_in_progress": "Ottimizzazione in corso...",
            "encountered_error": "Errore Riscontrato",
            "json_debug_description": "Questo è il pacchetto dati inviato all'IA. Utile per il debug dei '0 suggerimenti'.",
            "json_detail": "Dettaglio JSON",
            "diagnostics_log": "Log Diagnostica",
            "clear": "Cancella",
            "frequency_suggestion_prompt_fmt": "Sto pianificando l'orario ferroviario per la linea \"%@\".\nFermate: %@.\nTempo di sosta medio per fermata: 3 minuti.\n\nSuggerisci una frequenza oraria ottimale (es. ogni 30 min, ogni ora) basandoti sulla lunghezza del percorso e sul tipo di servizio (Regionale/Diretto). Fornisci una risposta concisa con la frequenza e una breve motivazione.",
            "ai_error_fmt": "Errore durante la richiesta AI: %@",
            "create_track_button": "Crea Binario",
            "current_path": "Percorso Corrente",
            "select_intermediate_station": "Seleziona Stazione Intermedia",
            "in_line": "Nella Linea",
            "train_label_fmt": "Treno: %@",
            "total_delay_label": "Totale Ritardo",
            "detailed_schedule": "Orario Dettagliato",
            "dwell_time_short": "Sosta",
            "platform_short": "Bin.",
            "timetable_detail": "Dettaglio Orario",
            "arrival_short": "A:",
            "departure_short": "P:",
            "solve_conflicts_button": "Risolvi Conflitti",
            "ai_limit_title": "Limite AI",
            "ai_too_many_trains_fmt": "Troppi treni (%d). Il limite massimo per l'ottimizzazione AI è 50 treni. Riduci il numero di treni e riprova.",
            "add_station_upstream": "Aggiungi stazione a monte",
            "add_station_downstream": "Aggiungi stazione a valle",
            "dwell_time_min": "%d min",
            "danger_zone": "Zona Pericolo",
            "reset_all_data": "Elimina Tutto (Rete e Treni)",
            "reset_confirm_title": "Conferma Eliminazione",
            "reset_confirm_message": "Sei sicuro di voler eliminare l'intera rete, tutte le linee e tutti i treni? Questa azione non può essere annullata."
        ],
        .english: [
            "settings": "Settings",
            "language": "Language",
            "select_language": "Select Language",
            "network": "Network",
            "lines": "Lines",
            "trains": "Trains",
            "railway_ai": "Railway AI",
            "io": "I/O",
            "visualization": "Visualization",
            "diagnostics": "Diagnostics",
            "ai_config": "AI Configuration",
            "performance": "Performance",
            "global_line_width": "Global Line Width",
            "global_font_size": "Global Font Size",
            "track_widths": "Track Widths",
            "track_single": "Single Track",
            "track_double": "Double Track",
            "track_regional": "Regional Track",
            "track_highspeed": "High Speed",
            "train_params": "Train Parameters",
            "max_speed": "Max Speed (km/h)",
            "acceleration": "Acceleration (m/s²)",
            "deceleration": "Deceleration (m/s²)",
            "priority": "Priority (1-10)",
            "track_speed_limits": "Track Speed Limits",
            "station": "Station",
            "interchange": "Interchange",
            "depot": "Depot",
            "junction": "Junction",
            "export": "Export",
            "print": "Print",
            "undo": "Undo",
            "redo": "Redo",
            "save": "Save",
            "delete": "Delete",
            "edit": "Edit",
            "add": "Add",
            "search": "Search...",
            "name": "Name",
            "type": "Type",
            "capacity": "Capacity",
            "platforms": "Platforms",
            "departure": "Departure",
            "arrival": "Arrival",
            "dwell_time": "Dwell (min)",
            "track": "Track",
            "no_trains": "No Trains",
            "no_stations": "No Stations",
            "no_lines": "No Lines",
            "loading": "Loading...",
            "error": "Error",
            "success": "Success",
            "confirm": "Confirm",
            "file_management": "File Management",
            "save_project": "Save Project",
            "open_project": "Open Project",
            "save_local": "Save Current State",
            "save_local_desc": "Quick save to local database",
            "legacy_integration": "Legacy Integration",
            "legacy_footer": "Import files from previous versions (FDC 1.x) to convert them to the Pignolo protocol.",
            "import_old": "Import Old FDC (.fdc)",
            "export_new": "Export Pignolo V2 (.rail)",
            "io_title": "I/O Data",
            "support_format": "Supports .rail, .fdc, .json",
            "done": "Done",
            "cancel": "Cancel",
            "show_all": "Show All",
            "filter": "Filter",
            "search_station": "Search station...",
            "empty_line": "Empty Line",
            "no_connection": "No Connection",
            "show_all_anyway": "Show all stations anyway",
            "must_create_stations": "You must first create stations in the 'Network' section.",
            "select_station": "Select Station",
            "edit_station": "Edit Station",
            "close": "Close",
            "delete_station": "Delete Station",
            "delete_confirm": "Are you sure you want to delete this station? This action cannot be undone.",
            "station_data": "Station Data",
            "station_name": "Station Name",
            "functional_type": "Functional Type",
            "standard_station": "Standard Station",
            "platform_count": "Platform Count",
            "hubs_interchanges": "Hubs & Interchanges",
            "belongs_to_hub": "Belongs to HUB",
            "no_hub": "No HUB (Independent)",
            "visual_style": "Visual Style",
            "coordinates": "Coordinates",
            "latitude": "Latitude",
            "longitude": "Longitude",
            "move_mode": "Move Mode",
            "move_mode_on": "ACTIVE: You can drag the station on the map or type coordinates.",
            "move_mode_off": "INACTIVE: Position is locked to prevent accidental moves. Enable to edit.",
            "custom_color": "Custom Color",
            "details": "Details",
            "general_options": "General Options",
            "show_grid": "Show Grid",
            "use_cloud_ai": "Conflict Resolution via Cloud AI",
            "sizes": "Sizes",
            "line_width_px": "Line Width: %d px",
            "font_size_pt": "Font Size: %d pt",
            "track_widths_map": "Track Widths on Map",
            "track_single_px": "Single Track: %.1f px",
            "track_double_px": "Double Track: %.1f px",
            "track_regional_px": "Regional Track: %.1f px",
            "track_highspeed_px": "High Speed Track: %.1f px",
            "reset_defaults": "Reset to Defaults",
            "map_preview": "Map Preview",
            "example_station": "EXAMPLE STATION",
            "regional_line": "Regional Line",
            "edge_representation": "Link Representation",
            "server_config": "Server Configuration",
            "api_base_url": "Server API Base URL",
            "restore_default_url": "Restore default URL",
            "username": "Username",
            "password": "Password",
            "permanent_api_key": "Permanent API Key",
            "auth_footer": "Use Password for temporary login or API Key for permanent access.",
            "authentication": "Authentication",
            "test_login": "Test Login",
            "generate_api_key": "Generate API Key",
            "login_success": "Login Successful! Token saved.",
            "login_error": "Login Error: %@",
            "api_key_generated": "API Key Generated and Saved!",
            "api_key_error": "Error Generating Key: %@",
            "ai_api_key_auth": "API Key Authentication",
            "ai_get_key_instruction": "To get your API Key:",
            "ai_step_1": "1. Go to the Railway AI dashboard",
            "ai_step_2": "2. Login with your credentials",
            "ai_step_3": "3. Copy your API Key from the dashboard",
            "ai_step_4": "4. Paste it in the field above",
            "ai_open_dashboard": "Open Railway AI Dashboard",
            "ai_verify_key": "Verify API Key",
            "ai_key_invalid": "Invalid API Key: %@",
            "ai_key_valid_fmt": "✓ Valid API Key - User: %@ - Expires in: %d days",
            "ai_key_expiring_fmt": "⚠️ Warning: Key expires in %d days!",
            "diagnostics_and_info": "Diagnostics & Info",
            "show_network_logs": "Show Network Logs",
            "info": "Information",
            "credits_author": "Credits & Author",
            "debug_data_json": "Debug Data (JSON)",
            "show_json_lines": "Show Line JSON",
            "show_json_trains": "Show Train JSON",
            "hub_position": "Hub Position",
            "hub_standard_pos": "Standard (Bottom Left)",
            "hub_logic_description": "This station is logically linked to another. It will be treated as a rapid interchange point.",
            "track_properties": "Track Properties",
            "distance_km": "Distance (km)",
            "distance": "Distance",
            "max_speed_kmh": "Max Speed (km/h)",
            "speed": "Speed",
            "track_type": "Track Type",
            "capacity_trains_h": "Capacity (trains/h)",
            "delete_track": "Delete Track",
            "edit_track": "Edit Track",
            "delete_track_confirm": "Are you sure you want to delete this track? This action cannot be undone.",
            "selection": "Selection",
            "trains_selected_count": "%d trains selected",
            "plus_others_count": "+ others %d",
            "quick_actions": "Quick Actions",
            "shift_time_minutes": "Shift Time: %@%d min",
            "apply_shift": "Apply Shift",
            "delete_selected": "Delete Selected",
            "batch_edit": "Batch Edit",
            "delete_trains": "Delete Trains",
            "delete_trains_confirm": "Are you sure you want to delete %d trains? This action is not reversible.",
            "select_category": "Select a category",
            "exporting_in_progress": "Exporting in progress...",
            "current_screen": "Current Screen",
            "export_jpg": "Export JPG",
            "export_pdf": "Export PDF",
            "map": "Map",
            "high_res_map": "High Resolution Map",
            "print_job_map": "FdC Map Print",
            "stations": "Stations",
            "tracks": "Tracks",
            "stations_count": "Stations (%d)",
            "tracks_count": "Tracks (%d)",
            "edit_line": "Edit Line",
            "delete_line": "Delete Line",
            "no_trains_assigned": "No trains assigned to this line.",
            "unassigned_trains": "Unassigned Trains",
            "schedule_management": "Schedule Management",
            "delete_all_trains": "Delete All Trains",
            "delete_all_trains_help": "Delete all trains from the system (including ghost trains)",
            "ai_suggestion_alert": "AI Suggestion",
            "ok": "Ok",
            "default_train_params": "Default Train Parameters",
            "new_train_params_desc": "These parameters are used when creating a new train",
            "regional_train": "Regional Train",
            "intercity_train": "Intercity Train",
            "highspeed_train": "High Speed Train",
            "max_speed_label": "Max Speed:",
            "acceleration_label": "Acceleration:",
            "deceleration_label": "Deceleration:",
            "priority_label": "Priority:",
            "track_speed_limits_section": "Track Speed Limits",
            "track_speed_limits_desc": "Speed limits for track types",
            "train_track_params_title": "Train & Track Parameters",
            "path_composition": "Path Composition",
            "line_details": "Line Details",
            "line_name_placeholder": "Line Name",
            "code_prefix_placeholder": "Code Prefix (e.g. RE)",
            "number_prefix_placeholder": "Numeric Prefix",
            "line_color": "Line Color",
            "new_line": "New Line",
            "line_name_example": "Line Name (e.g. London-Paris)",
            "number_prefix_example": "Numeric Prefix (e.g. 5)",
            "train_details": "Train Details",
            "number": "Number",
            "name_optional": "Name (optional)",
            "train_type_picker": "Type",
            "departure_picker": "Departure",
            "selected_line": "Selected Line",
            "stop_sequence": "Stop Sequence",
            "select_terminals_desc": "Select terminals or add manually",
            "add_stop_manual": "Add manual stop",
            "new_trip": "New Trip",
            "create": "Create",
            "train_name_default": "Train %d",
            "freight_train": "Freight Train",
            "support_train": "Support Train",
            "developed_by": "Developed by",
            "version_label": "Version %@",
            "project_info_title": "Project Information",
            "project_description": "FdC Railway Manager is an advanced tool for management, simulation, and optimization of local railway networks. It integrates pathfinding algorithms, conflict detection, and artificial intelligence to ensure efficient and safe schedules.",
            "technologies_used": "Technologies used:",
            "reactive_interface": "Reactive Interface",
            "ml_optimization": "ML Optimization",
            "geographic_visualization": "Geographic Visualization",
            "credits": "Credits",
            "no_stations_system": "There are no stations registered in the system.",
            "line_no_stations": "This railway line has no stations assigned yet. Add them in the 'Lines' tab.",
            "no_connected_tracks": "There are no tracks connecting the last selected station to other nodes. Draw a track or show all stations.",
            "no_stations_criteria": "No stations match the search criteria.",
            "current_project": "Current Project",
            "unnamed_network": "Unnamed Network",
            "stations_count_label": "%d stations",
            "tracks_count_label": "%d tracks",
            "lines_count_label": "%d lines",
            "trains_count_label": "%d trains",
            "last_save": "Last save: %@",
            "quick_save": "Quick Save",
            "save_current_state": "Save Current State",
            "auto_save_local_desc": "Automatic save to local database",
            "import_export_files": "File Import / Export",
            "export_project": "Export Project",
            "save_rail_file_desc": "Save as .rail file (Pignolo V2)",
            "import_project": "Import Project",
            "support_formats_desc": "Supports .rail, .fdc, .railml, .json",
            "legacy_formats": "Legacy Formats",
            "legacy_formats_footer": "Import files created with previous versions (FDC 1.x) to automatically convert them to the new Pignolo V2 protocol.",
            "import_fdc_legacy": "Import Legacy FDC (.fdc)",
            "import_railml": "Import RailML (.railml)",
            "import_error_title": "Import Error",
            "security_scoped_error": "Unable to gain access to the file (Security Scoped Resource)",
            "decode_error": "Unable to decode the file. Format not recognized.",
            "io_management": "I/O Management",
            "smart_scheduling_intel": "Smart Scheduling Intelligence",
            "optimize_button": "Optimize",
            "system_status": "System Status",
            "trains_count": "%d Trains",
            "stations_label": "Stations",
            "segments_label": "Segments",
            "status_label": "Status",
            "waiting_status": "Waiting",
            "optimized_status": "Optimized",
            "proposed_modifications": "Proposed Modifications",
            "no_modifications_needed": "No modifications needed. Optimal schedule.",
            "optimization_analysis": "Optimization Analysis",
            "detected_label": "Detected",
            "resolved_label": "Resolved",
            "remaining_label": "Remaining",
            "residual_conflicts_detail": "Residual Conflicts Detail",
            "total_optimized_time": "Total Optimized Time",
            "ready_for_optimization": "Ready for Optimization",
            "ai_welcome_desc": "Load trains and click Optimize to use RailwayAI and resolve all network conflicts.",
            "ai_analyzing": "AI Analysis in progress...",
            "platform_at": "Platform %d",
            "modification": "Modification",
            "impact_label": "Impact: %ds",
            "trains_to_schedule": "Trains to Schedule",
            "manage_trains": "Manage Trains",
            "type_speed_label": "Type: %@, Max speed: %d km/h",
            "timetable_traffic_sim": "Timetable and Traffic Simulation",
            "calculate_timetables": "Calculate Timetables and Conflicts",
            "calculating_in_progress": "Calculation in progress...",
            "export_result": "Export Result",
            "view_timetable_chart": "View Timetable Chart",
            "local_infrastructure": "Local Infrastructure (FDC Engine)",
            "simulate_full_network": "Simulate Full Network",
            "stops_count_label": "%d stops",
            "conflict_dashboard": "Conflict Dashboard",
            "manual_timetable_edit": "Manual Timetable Editing",
            "edit_timetables_manually": "Edit Timetables Manually",
            "advanced_export_print": "Advanced Export and Print",
            "copy_to_clipboard": "Copy Result to Clipboard",
            "print_result": "Print Result",
            "file_import": "File Import",
            "import_fdc_txt": "Import .fdc or .txt file",
            "timetables_conflicts_result": "Timetables/Conflicts Result",
            "detected_conflicts": "Detected Conflicts",
            "scheduler_title": "Scheduler",
            "import_fdc_button": "Import .fdc",
            "manage_trains_title": "Manage Trains",
            "add_train": "Add Train",
            "new_train": "New Train",
            "train_name": "Train Name",
            "add_button": "Add",
            "timetable_chart_title": "Train Timetable Chart",
            "manual_edit_title": "Manual Timetable and Conflict Edit",
            "print_preview_title": "Print Preview",
            "print_job_scheduler": "Timetables and Conflicts",
            "network_load_error": "Error loading network: %@",
            "network_save_error": "Error saving network: %@",
            "single_trip": "Single Trip",
            "cadenced_trip": "Cadenced",
            "even": "Even",
            "odd": "Odd",
            "outward": "Outward",
            "return": "Return",
            "genetic_opt_gen_fmt": "Genetic Optimization (Gen %d)",
            "conflicts_count_fmt": "%d conflicts",
            "cancelling": "Cancelling...",
            "stop": "Stop",
            "generate": "Generate",
            "schedule_generation": "Schedule Generation",
            "schedule_gen_line_fmt": "Schedule Generation - Line %@",
            "mode": "Mode",
            "from": "From",
            "to": "To",
            "via": "Via",
            "path": "Path",
            "stations_count_fmt": "%d stations",
            "length_short": "Len.",
            "est_duration_short": "Est. duration",
            "duration_min_fmt": "%d min",
            "train_type": "Train Type",
            "start_hour": "Start Hour",
            "end_hour": "End Hour",
            "interval": "Interval",
            "interval_min_fmt": "%d min",
            "start_number": "Start Number",
            "num_placeholder": "Num",
            "parity": "Parity",
            "trains_to_be_created_fmt": "%d trains will be created.",
            "optimization_ga": "Optimization (GA)",
            "cloud_ai_active_desc": "Cloud AI Optimization Active (Global).",
            "local_ga_desc": "Local G.A. will adjust departures and dwells to eliminate conflicts.",
            "path_mode": "Path Mode",
            "method": "Method",
            "auto_calculation": "Auto Calculation",
            "manual_composition": "Manual Composition",
            "define_terminals": "Define Terminals",
            "via_passage": "Pass via",
            "add_via_point": "Add via point",
            "invert_path_desc": "Invert Path (B -> A)",
            "calculating_path_desc": "Calculating path...",
            "calculate_proposed_paths": "Calculate Proposed Paths",
            "proposed_path": "Proposed Path",
            "select_dots": "Select...",
            "path_alt_fmt": "%@ (%d stops, %.1f km)",
            "path_found_fmt": "Path found: %@",
            "total_distance": "Total distance:",
            "calculated_itinerary": "Calculated itinerary:",
            "manual_composition_desc": "Use the section below to manage the station sequence.",
            "error_index_not_found_fmt": "Error: Index not found (%d)",
            "unknown_station": "Unknown",
            "error_stations_not_in_line": "Stations not found in selected line.",
            "error_select_terminals": "Select at least a start and end station.",
            "error_no_path_found_fmt": "No path found between %@ and %@.",
            "multi_line_path": "Multi-line Path",
            "error_no_simple_path": "No simple path found connecting all stops.",
            "line_analysis": "Line analysis...",
            "starting_pipeline": "Starting 7-Step Pipeline...",
            "preparation": "Preparation...",
            "sending_to_cloud": "Sending to Cloud...",
            "applying": "Applying...",
            "validation": "Validation...",
            "final_refinement": "Final Refinement...",
            "optimized": "Optimized!",
            "almost_resolved_fmt": "Almost resolved (%d remaining)",
            "filled_star": "Filled Star",
            "filled_square": "Filled Square",
            "empty_square": "Empty Square",
            "filled_circle": "Filled Circle",
            "empty_circle": "Empty Circle",
            "top_left_offset": "Top Left",
            "top_right_offset": "Top Right",
            "bottom_left_offset": "Bottom Left",
            "bottom_right_offset": "Bottom Right",
            "unnamed_line": "Unnamed Line",
            "all_tab": "All",
            "hotspots_tab": "Hotspots",
            "lines_tab": "Lines",
            "line_segments": "Line Segments",
            "nodes_stations": "Nodes/Stations",
            "perfect_timetable": "Perfect Timetable",
            "no_conflicts_desc": "The algorithm has resolved all conflicts. The plan is ready for operation.",
            "conflicts_detected_fmt_short": "%d Conflicts Detected",
            "conflict_analysis_desc": "Temporal collision and saturated resources analysis",
            "criticality": "Criticality",
            "consecutive_collisions": "Consecutive collisions at this point",
            "export_completed": "✅ Export completed",
            "export_error_fmt": "Export error: %@",
            "import_completed_fmt": "✅ Import completed: %@",
            "import_error_fmt": "Load error: %@",
            "railml_parsing_failed": "RailML parsing failed",
            "loaded_rail_file_fmt": "✅ Loaded .rail file: %@",
            "ai_optimizer_fdc": "FDC Optimizer (v1/v2)",
            "solve_conflicts_json": "Solve Conflicts (FDC JSON)",
            "advanced_optimizer_cpp": "Advanced Optimizer (GA C++)",
            "global_optimization_pignolo": "Global Optimization (Pignolo)",
            "conflicts_detected_fmt": "Conflicts detected: %d",
            "total_delay_fmt": "Total delay: %.1f min",
            "planning_assistant_fast": "Planning Assistant (Fast Proposer)",
            "target_lines_fmt": "Target Lines: %d",
            "generate_schedule_proposal": "Generate Schedule Proposal",
            "review_proposals_fmt": "Review Proposals (%d lines)",
            "optimized_solutions": "Optimized Solutions",
            "departure_adj_fmt": "Departure: %@%.1f min",
            "dwells_extended_fmt": "%d extended dwells",
            "schedules_updated_success": "Schedules updated successfully.",
            "apply_schedule_change": "Apply Schedule Change",
            "proposed_solutions": "Proposed Solutions",
            "unknown_train": "Unknown Train",
            "new_departure_fmt": "New Departure: %@",
            "modified_stops_fmt": "Modified stops: %d",
            "apply_changes_button": "Apply Changes",
            "changes_applied_success": "Changes applied successfully.",
            "last_operation_result": "Last Operation Result",
            "json_inspection_request": "JSON Inspection Requested",
            "optimization_in_progress": "Optimization in progress...",
            "encountered_error": "Encountered Error",
            "json_debug_description": "This is the data packet sent to the AI. Useful for debugging '0 suggestions'.",
            "json_detail": "JSON Detail",
            "diagnostics_log": "Diagnostics Log",
            "clear": "Clear",
            "frequency_suggestion_prompt_fmt": "I'm planning the railway schedule for the line \"%@\".\nStops: %@.\nAverage dwell time per stop: 3 minutes.\n\nSuggest an optimal hourly frequency (e.g., every 30 min, every hour) based on route length and service type (Regional/Direct). Provide a concise response with the frequency and a brief rationale.",
            "ai_error_fmt": "Error during AI request: %@",
            "create_track_button": "Create Track",
            "current_path": "Current Path",
            "select_intermediate_station": "Select Intermediate Station",
            "in_line": "In Line",
            "train_label_fmt": "Train: %@",
            "total_delay_label": "Total Delay",
            "detailed_schedule": "Detailed Schedule",
            "dwell_time_short": "Dwell",
            "platform_short": "Pl.",
            "timetable_detail": "Timetable Detail",
            "arrival_short": "A:",
            "departure_short": "D:",
            "solve_conflicts_button": "Solve Conflicts",
            "ai_limit_title": "AI Limit",
            "ai_too_many_trains_fmt": "Too many trains (%d). The maximum limit for AI optimization is 50 trains. Reduce the number of trains and try again.",
            "add_station_upstream": "Add upstream station",
            "add_station_downstream": "Add downstream station",
            "dwell_time_min": "%d min",
            "danger_zone": "Danger Zone",
            "reset_all_data": "Delete All (Network & Trains)",
            "reset_confirm_title": "Confirm Deletion",
            "reset_confirm_message": "Are you sure you want to delete the entire network, all lines, and all trains? This action cannot be undone."
        ]
    ]
}

extension String {
    var localized: String {
        return LocalizationManager.shared.string(for: self)
    }
}
